### ISSUE TITLE
[Bug] nuget package target .netcoreapp 3.1 has dependency on Xamarin.Forms.Platform.WPF which breaks on mac buildagent

### ISSUE THREAD

**Issue by rikbosch** [xamarin/XamarinCommunityToolkit#968] opened 2021-02-23 16:01 UTC
### Description

The Xamarin.CommunityToolkit has a dependency on Xamarin.Forms.Platform.WPF when targetting .netcoreapp3.1. Xamarin.Forms.Platform.WPF in turn is dependent on OpenTK, which is not compatible with .netcoreapp3.1

from our build logs:

```
warning NU1701: Package 'OpenTK 3.0.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.

warning NU1701: Package 'OpenTK.GLControl 3.0.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.

/usr/local/share/dotnet/sdk/5.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(324,5): error NETSDK1073: The FrameworkReference 'Microsoft.WindowsDesktop.App' was not recognized [/Users/administrator/devops-agents/_work/1/s/src/DriverApp.UnitTests/DriverApp.UnitTests.csproj]

```

Our testproject does have a FrameworkReference to Microsoft.WindowsDesktop.App

### Steps to Reproduce

1. Create an XUnit test project, targetting .netcoreapp3.1
2. Add packagereference to Xamarin.CommunityToolkit 1.0.3
3. run dotnet test on a mac

### Expected Behavior
Project builds and runs tests.

### Actual Behavior
Build fails with `error NETSDK1073: The FrameworkReference 'Microsoft.WindowsDesktop.App' was not recognized `

### Basic Information

- Version with issue: 1.0.3
- Last known good version: unknown
- IDE: Visual Studio 2019 (paired to mac)
- Platform Target Frameworks:
  - iOS:  Xamarin IOS 14.8
  - netcoreapp3.1
- Affected Devices:
  - mac build agent

**Comment by brminnick** [comment] 2021-02-23 18:52
Duplicate of https://github.com/xamarin/XamarinCommunityToolkit/issues/876

**Comment by brminnick** [comment] 2021-02-23 18:52
### Workaround

The current workaround is to add the following line to the Unit Test CSPROJ file:

```xml
<GenerateErrorForMissingTargetingPacks>false</GenerateErrorForMissingTargetingPacks>
```

Here an example of I implement this workaround in my app GitTrends:
https://github.com/brminnick/GitTrends/blob/efe0f6e06c1e22c444b2fa35646797c64e82f235/GitTrends.UnitTests/GitTrends.UnitTests.csproj#L9

**Closed by brminnick** 2021-02-23 18:52 UTC
Labels: bug, s/unverified

**Comment by rikbosch** [comment] 2021-02-23 19:22
@brminnick thanks! I've searched open issues but did not see the duplicate.

Thanks for quick response.
