### ISSUE TITLE
[Bug] MediaElement throws NullReferenceException paper cut

### ISSUE THREAD

**Issue by davidbritch** [xamarin/XamarinCommunityToolkit#414] opened 2020-02-17 11:32 UTC
### Description

`MediaElement` throws a `NullReferenceException` when calling the `Play`, `Pause`, and `Stop` methods when a `Source` hasn't been specified. Obviously this can be coded around by only calling those methods dependent upon the `CurrentState` property. So this is a paper cut rather than a bug.

Perhaps the UWP approach should be adopted, which is that "Any calls to Play, Pause, and Stop methods that occur before the MediaOpened event is raised are ignored."

**Comment by daniel-shuy** [comment] 2020-10-19 15:26
@davidbritch Did you face this on Android or iOS or both?

**Comment by davidbritch** [comment] 2020-10-19 16:26
@daniel-shuy I just gave it a try and the exception is on iOS only (only tried iOS + Android).

**Comment by daniel-shuy** [comment] 2020-10-20 08:37
@davidbritch thanks, do you also happen to have a stack trace?

**Comment by davidbritch** [comment] 2020-10-20 09:26
@daniel-shuy 

  at Xamarin.Forms.Platform.iOS.MediaElementRenderer.MediaElementVolumeRequested (System.Object sender, System.EventArgs e) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\MediaElementRenderer.cs:383 
  at Xamarin.Forms.Platform.iOS.MediaElementRenderer.MediaElementStateRequested (System.Object sender, Xamarin.Forms.StateRequested e) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\MediaElementRenderer.cs:318 
  at Xamarin.Forms.MediaElement.Play () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\MediaElement.cs:177 
  at MediaElementDemos.CustomTransportPage.OnPlayPauseButtonClicked (System.Object sender, System.EventArgs args) [0x00032] in /Users/davidbritch/Downloads/Xamarin_Forms___MediaElement/MediaElementDemos/Views/CustomTransportPage.xaml.cs:19 
  at Xamarin.Forms.Button.Xamarin.Forms.Internals.IButtonElement.PropagateUpClicked () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Button.cs:187 
  at Xamarin.Forms.ButtonElement.ElementClicked (Xamarin.Forms.VisualElement visualElement, Xamarin.Forms.Internals.IButtonElement ButtonElementManager) [0x0001f] in D:\a\1\s\Xamarin.Forms.Core\ButtonElement.cs:61 
  at Xamarin.Forms.Button.SendClicked () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Button.cs:173 
  at Xamarin.Forms.Platform.iOS.ButtonElementManager.OnButtonTouchUpInside (Xamarin.Forms.IButtonController element) [0x00009] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\ButtonElementManager.cs:86 
  at Xamarin.Forms.Platform.iOS.ButtonRenderer.OnButtonTouchUpInside (System.Object sender, System.EventArgs eventArgs) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\ButtonRenderer.cs:190 
  at UIKit.UIControlEventProxy.Activated () [0x00004] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.0.0.0/src/Xamarin.iOS/UIKit/UIControl.cs:38 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.0.0.0/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.0.0.0/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at MediaElementDemos.iOS.Application.Main (System.String[] args) [0x00001] in /Users/davidbritch/Downloads/Xamarin_Forms___MediaElement/MediaElementDemos.iOS/Main.cs:17

**Comment by daniel-shuy** [comment] 2020-10-20 09:52
I've created a PR which should fix this issue

**Comment by daniel-shuy** [comment] 2020-10-21 02:02
@davidbritch looking closer at your stack trace, I think you are using `Xamarin.Forms`, not the `XamarinCommunityToolkit`, this bug doesn't belong here

**Comment by AndreiMisiukevich** [comment] 2020-10-21 07:57
> @davidbritch looking closer at your stack trace, I think you are using `Xamarin.Forms`' `MediaElement`, not the `Xamarin.CommunityToolkit`'s `MediaElement` (see https://github.com/xamarin/XamarinCommunityToolkit/wiki/Features-moved-from-Xamarin.Forms#user-content-mediaelement on how to use the `Xamarin.CommunityToolkit`'s `MediaElement`).
> 
> You may want to retry all your `MediaElement` issues with the `Xamarin.CommunityToolkit`'s `MediaElement` instead.

This issue was moved from Xamarin.Forms repository to this repo. That's why the stack shows XF stack trace

**Comment by jfversluis** [comment] 2020-10-21 08:50
Seems this is not able to reproduce anymore when this was transferred to the Toolkit and can be closed

@daniel-shuy yeah it's a bit of a weird situation with these things moving. So it would be wise to re-verify all these things

**Closed by jfversluis** 2020-10-21 08:50 UTC
Labels: a/MediaElement, bug
