### ISSUE TITLE
[Enhancement] Simple Navigation Service

### ISSUE THREAD

**Issue by mgierlasinski** [xamarin/XamarinCommunityToolkit#240] opened 2020-08-26 06:59 UTC
## Summary

Default navigation in Xamarin Forms is heavily page-based, this is usually not what you expect when working with View Models. If you don't use any framework or shell, with new project you end up writing another INavigationService. Again. 

## API Changes

API similar to Prism or MvvmCross:
```
var navigation = DependencyService.Resolve<INavigationService>();
navigation.Navigate<TViewModel>();
navigation.Navigate<TViewModel, TParameter>(TParameter param);
```

Extra:
```
TResult result = await navigation.Navigate<TViewModel, TParameter, TResult>(TParameter param);
```

### Interfaces for view models
```
interface INavigationAware
{
    void OnNavigated(object parameter);
}

interface INavigationAware<TParam>
{
    void OnNavigated(TParam parameter);
}
```
### Map pages to view models
```
[ViewModel(typeof(MyPageViewModel))]
public class MyPage : ContentPage
{
{
```
## Intended Use Case
Easily navigate between view models without referencing Xamarin Forms UI components and without any frameworks.

**Comment by michaldivis** [comment] 2020-10-06 09:22
Are you currently working on this or can I?

**Comment by mgierlasinski** [comment] 2020-10-07 05:58
@michaldivis Nope, I've just thrown an idea, go ahead :)

**Comment by AbuMandour** [comment] 2020-11-09 08:22
@jfversluis I think that this request is smaller to my request #194, please reconsider this :), at all am not alone in this 😅😅

**Comment by jfversluis** [comment] 2020-11-09 08:32
> and without any frameworks.

Well, technically this is another framework, right? :)
 
I mean, I see what you're trying to accomplish, but it's a slippery slope. Then we can start adding all the libraries into one just so we don't have to install any others anymore. 

The thing with this is: if we start out with this navigation service, then the next thing will be: I want {another feature x of MVVM framework y} because then I don't need another framework. And before we know it, we are again building (another) MVVM framework.

What would be the use-case here? Will this single feature eliminate the need for installing an MVVM framework into your application? Is this the only, single value all of those MVVM frameworks are providing?

Please don't read any of this in a bad way, I am honestly trying to figure out what we should do with this. Because you are right: these requests will keep coming and I'm trying to figure out where to draw the line. I definitely see your standpoint, I hope you can also see mine :D

**Comment by AbuMandour** [comment] 2020-11-09 09:22
@jfversluis why I will read this in a bad way, talks always generate good ideas my friend
May I am afraid another MVVM framework support and configuration but anyway Thanks ☺️

**Comment by mgierlasinski** [comment] 2020-11-16 18:00
@jfversluis @AbuMandour  The idea here is to have some sort of navigation that we can use in view models out of the box so we don't have to reinvent the wheel each time we start a new project. Default navigation is very page-based and tightly coupled which doesn't play well with non-coupled VMs. Let's look at Shell - we start new project and only thing we need to do to navigate is to map routes to Pages. It would be great if something similar was available for classic Forms app.

**Comment by pictos** [comment] 2020-11-28 19:54
I agree with @jfversluis I think is out of the scope of this project. This proposal fits better in this [repo/project](https://github.com/xamcat/mobcat-library).

**Comment by Cfun1** [comment] 2021-01-08 18:10
@jfversluis , @pictos confirmed that this is out of scope or still some discussion needed ?

**Comment by jfversluis** [comment] 2021-01-08 19:09
I still think this is out of scope. Also have a look at the Windows Community Toolkit. They might have something to better fit these needs.

**Closed by jfversluis** 2021-01-08 19:09 UTC
Labels: feature-request, needs-more-discussion
