### ISSUE TITLE
Fix up XML comments

### ISSUE THREAD

**Issue by bartlannoeye** [xamarin/XamarinCommunityToolkit#13] opened 2017-02-16 16:24 UTC
_From @jimbobbennett on December 22, 2016 22:52_

XML comments are missing from the effects, and need to be added.

_Copied from original issue: FormsCommunityToolkit/Effects#33_

**Comment by jsuarezruiz** [comment] 2018-03-13 20:36
Do we check all the libraries to add the XML comments?. I can send a PR.

**Comment by bartlannoeye** [comment] 2018-03-14 08:02
Probably not yet, wouldn't add them as build errors until we take some time to fix it in the first place (with correct comments, not just comments for the sake of it).

**Comment by jamesmontemagno** [comment] 2018-04-05 19:51
Will be a duplicate of #76 we will remove all xml docs and use mdoc

**Closed by jamesmontemagno** 2018-04-05 19:51 UTC
Labels: help wanted
