### ISSUE TITLE
MT2101: Can't resolve the reference 'Xamarin.Forms.MediaSource'

### ISSUE THREAD

**Issue by KMWenyon** [xamarin/XamarinCommunityToolkit#439] opened 2020-10-12 14:29 UTC
### Description
/Users/UserName/TFS/AppSolutionFolder/com.namespace.app.ios/MTOUCH: Error MT2101: Can't resolve the reference 'Xamarin.Forms.MediaSource', referenced from the method 'System.Void Xamarin.CommunityToolkit.UI.Views.MediaCapturedEventArgs::.ctor(System.String,System.Byte[])' in 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. (MT2101) (com.namespace.app.ios)

### Steps to Reproduce

1. Upgrade to Xamarin.Forms 5.0.0.1539-pre2
2. Install Xamarin Community Toolkit (1.0.0-pre3)
3. build solution

### Expected Behavior
Build to complete without error and deploy to iOS device

### Actual Behavior
Build Fails with the afore mentioned error

### Basic Information

- Version with issue: Don't know just upgrading to use Expander
- Last known good version: Don't know just upgrading to use Expander
- IDE: VS MAC 8.7.2 (build 4)
- Platform Target Frameworks: 
  - iOS:  Default
  - Android: 10.0 Api 29
  - UWP:  N/A
- Android Support Library Version: 28.0.0.3
- Nuget Packages:
- Affected Devices: iOS (Android Builds and Deploys to Devices)

### Reproduction Link

=== Visual Studio Professional 2019 for Mac ===

Version 8.7.2 (build 4)
Installation UUID: f644610c-a365-48d8-a3bf-a3e34d38feed
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000090

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.90 (2020-02/d3daacdaa80) (64-bit)
	Package version: 612000090

=== Roslyn (Language Service) ===

3.7.0-6.20371.12+917b9dfae12e3b6cb266a3c062fb20a1e9d5fb06

=== NuGet ===

Version: 5.7.0.6702

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.401/Sdks
SDK Versions:
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.1.701
	2.1.700
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.6 (16141)
Build 11E708

=== Xamarin.Mac ===

Version: 6.20.2.2 (Visual Studio Professional)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:44:59-0400

=== Xamarin.iOS ===

Version: 13.20.2.2 (Visual Studio Professional)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:45:00-0400

=== Xamarin Designer ===

Version: 16.7.0.492
Hash: f5afe667d
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-07-10 18:42:54 UTC

=== Xamarin.Android ===

Version: 11.0.0.3 (Visual Studio Professional)
Commit: xamarin-android/d16-7/aca845b
Android SDK: /Users/UserName/Library/Android/sdk
	Supported Android versions:
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.1

Build Information: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-7@1f3388a
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/UserName/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/dev/jmt/d16-7readconfig~2
Build date: 2020-07-23 22:38:02 UTC

=== Android Device Manager ===

Version: 16.7.0.18
Hash: 4b44bc1
Branch: remotes/origin/d16-7
Build date: 2020-07-23 22:38:26 UTC

=== Build Information ===

Release ID: 807020004
Git revision: 6b86e771c92aa2615d2c2a09919bb3d4ccb69a5a
Build date: 2020-08-12 07:16:26-04
Build branch: release-8.7
Xamarin extensions: 6b86e771c92aa2615d2c2a09919bb3d4ccb69a5a

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Mon Aug 31 22:12:52 PDT 2020
    root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

NuGet Package Explorer 0.5
NuGet Package Management Extensions 0.24

**Comment by jfversluis** [comment] 2020-10-13 17:15
@pictos this is fixed by #370, right?

**Comment by pictos** [comment] 2020-10-14 00:42
@jfversluis I believe so. Also, we can close this one because is a duplicate of #367

**Comment by jfversluis** [comment] 2020-10-14 06:59
Duplicate of #367

**Comment by jfversluis** [comment] 2020-10-14 06:59
And this should be fixed in the next release :)

**Closed by jfversluis** 2020-10-14 06:59 UTC
Labels: bug, s/unverified
