### ISSUE TITLE
How to set the text center of tabviewitem

### ISSUE THREAD

**Issue by bbhxwl** [xamarin/XamarinCommunityToolkit#1049] opened 2021-03-09 06:28 UTC
How to set the text center of tabviewitem

**Comment by Cfun1** [comment] 2021-03-09 08:31
Hi, it seems more of a question, if so you please close the issue and open a question in the [discussion section](https://github.com/xamarin/XamarinCommunityToolkit/discussions) instead. If it is a feature request could you please check if it isn't a duplicate of https://github.com/xamarin/XamarinCommunityToolkit/issues/776 ?

**Closed** 2021-03-16 23:02 UTC
Labels: feature-request, needs-approval
