### ISSUE TITLE
[Bug] UWP Sample app not working.

### ISSUE THREAD

**Issue by CliffAgius** [xamarin/XamarinCommunityToolkit#802] opened 2021-01-25 14:33 UTC
### Description

Built and ran the Sample app with UWP as the target and it runs but on selecting a page it shows nothing but a blank page rather than the controls it shoud.

### Steps to Reproduce

1. Clone and build the Sample App targeting UWP
2. Open the App and select a page to see it empty/blank.

### Expected Behavior

Should show the controls for that are of the sample app so that the user can see what they do on that platform.

### Actual Behavior

Shows blank/empty page.

### Basic Information

- Version with issue: V1
- Last known good version: Unknown only tried this version
- IDE: VS19 Windows
- Platform Target Frameworks: 
  - UWP:  18362

### Reproduction imagery

![1046C055-F9C8-4B55-9A38-93C80AB19035](https://user-images.githubusercontent.com/5613809/105719521-479a1200-5f1a-11eb-88ce-7229b98fbab2.GIF)

**Comment by redeaglekiller** [comment] 2021-01-25 23:33
The same happens to me. If you resize the window it shows content again....maybe something is broken with the navigation onready event. I'll look at it tomorrow.

Cheers

**Comment by pictos** [comment] 2021-01-26 00:04
Duplicate of #606

**Closed by pictos** 2021-01-26 00:04 UTC
Labels: bug, s/unverified

**Comment by jfversluis** [comment] 2021-01-26 10:25
Oh I thought we had an issue for that already, good catch @pictos :D

Let us know if you get to work on this @redeaglekiller would be good to get this fixed. Same happens on UWP and macOS. Although the latter is not fixed by a resize which could indicate it is another issue or macOS just draws their windows different :)
