### ISSUE TITLE
[Enhancement] Implement `IDisposable` on `Popup`

### ISSUE THREAD

**Issue by ArunPrakashG** [xamarin/XamarinCommunityToolkit#1176] opened 2021-04-06 16:29 UTC
## Summary

Currently, it's a little bit hard to control when to close the popup.
Implementing `IDisposable` Interface would introduce a `Dispose()` method which makes handling the popup easier.

## API Changes

Sample:
```csharp
using(PopupControl popup = new PopupControl("default_popup_text", lightDismisable: false)){
  // process stuff here
  // at the end, popup is automatically cancelled using Dispose()
  // update the progress on popup like so
  popup.Message = "test_message";
}
```
here, `PopupView` is a class which inherits `Popup` from XCT, With some added construct parameters on the base class and exposing of the `Message` property which Binded to the Popup UI. So Changing popup text will be easier as well.
by just doing `popup.Message = "new_text";`
`Dispose()` method will call `Dismiss(default)` which will cancel the popup.

## Intended Use Case
This will further simplify the process of creating, and closing the popup.

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by pictos** [comment] 2021-04-06 16:39
@ahoefling what do you think about this? TBH, I'm not sure if Forms handle that, just like he does for other xaml controls

**Comment by ahoefling** [comment] 2021-04-06 16:53
Currently Popup support several techniques for closing the popup
* Dismiss()
* LightDismiss()
* Async/Await pattern

As this specification is written if we implement `IDisposable` the popup will open and close immediately unless we do something to instruct it to dispose once the popup closes. This would create a blocking thread and prevent code from running until the object is disposed.

Could you describe the code-flow a little bit more and how you think it would handle the blocking thread in the `using` context?

**Comment by pictos** [comment] 2021-04-06 17:18
> As this specification is written if we implement IDisposable the popup will open and close immediately unless we do something to instruct it to dispose once the popup closes. This would create a blocking thread and prevent code from running until the object is disposed.

@ahoefling we can use `IAsyncDisposable` to avoid it (?), but yeah, I'm curious to see what's the intent use case

**Comment by ArunPrakashG** [comment] 2021-04-06 17:40
To better explain it, i will add the following example:
## PopupControl.xaml
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<xct:Popup xmlns="http://xamarin.com/schemas/2014/forms"
		   xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
		   xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
		   x:Class="SampleApp.Controls.PopupControl"
		   xmlns:controls="clr-namespace:SampleApp.Controls"		   
		   Color="Transparent"
		   Size="250,250"
		   x:DataType="controls:PopupControl"
		   HorizontalOptions="CenterAndExpand"
		   VerticalOptions="CenterAndExpand">
	<StackLayout>
		<Label Text="{Binding Message}"
			   TextColor="Black"
			   FontFamily="Ubuntu-Bold"
			   FontSize="15"
			   HorizontalTextAlignment="Center"
			   VerticalTextAlignment="Center"
			   VerticalOptions="FillAndExpand"
			   HorizontalOptions="FillAndExpand" />
	</StackLayout>
</xct:Popup>
```

## PopupControl.xaml.cs
```csharp
using System;
using System.Threading;
using Xamarin.CommunityToolkit.Extensions;
using Xamarin.CommunityToolkit.UI.Views;
using Xamarin.Forms;

namespace SampleApp.Controls {
	public partial class PopupControl : Popup, IDisposable {
		private string _message;

		public string Message {
			get => _message;
			set {
				_message = value;
				OnPropertyChanged(nameof(Message));
			}
		}

		public PopupControl(string message,  bool lightDissmissEnabled = false) {
			InitializeComponent();
			BindingContext = this;
			Message = message;
			IsLightDismissEnabled = lightDissmissEnabled;
		}

		public PopupControl Show() {
			Device.BeginInvokeOnMainThread(() => Shell.Current.Navigation.ShowPopup(this));
			return this;
		}

		public void Dispose() => Dismiss(default);

		public void SetPopupText(string text) => Device.BeginInvokeOnMainThread(() => Message = text);
	}
}

```
To display the popup, i call like so:
```csharp
using (PopupControl popup = new PopupControl("Loading...", default, false).Show()){
   // do some work here, if required   
}
```

once the `using` block finishes execution, `Dispose()` is called and which then dismisses the popup.
here the use case would be to display some quick information to the user, or a loading screen which indicates there is an activity going on
I am not very experienced. My apologies if there are mistakes in the code.

**Comment by ahoefling** [comment] 2021-04-06 19:47
Thank you for providing a detailed explanation of what you are thinking. My biggest area of concern is what is the expectation of the using block? By design popups have to wait until some action dismisses them. Adding a using block like this doesn't provide anyway to notify the popup of when to close.

If we implement `IDisosable` or `IAsyncDisposable` the popup would dismiss when the using block exits. This means you would need to manually add a thread sleep or event handler to to dispose of the object. An example below

```c#
using (var popup = new Popup().Show())
{
  // This code will make the popup flash and close, the popup will be on screen as fast as the device can render and dismiss
}
```

```c#
using (var popup = new Popup().Show())
{
  // This code will display the popup for 5000 ms and then dismiss the popup
  await Task.Delay(5000);
}
```

```c#
// This code will dispose of the popup via the event handler
var popup = new MyPopup();
popup.Show();
popup.ButtonTapped += (s, e) => popup.Dispose();
```

My evaluation of this specification - I don't think this makes sense to add to XCT as it doesn't provide a way to retain the popup without using `Task.Delay` or similar technique. If my evaluation of your spec is not correct, please provide details on how the popup will understand to remain on screen and how the using block will handle this.

**Comment by pictos** [comment] 2021-04-06 19:56
@ArunPrakashG thanks for your sample, I agree with @ahoefling here, And this isn't a good case scenario for using the Disposable pattern, I was thinking that you do something _heavier_ on your PopUp and need to clean up some resources at the end. For this scenario you can call the Dismiss method on your popUp and close it, does that works for you?

**Comment by ArunPrakashG** [comment] 2021-04-06 20:03
I understand the flaws in this.
so far, i only used the popups to display some activities like requesting REST api and indicate the request progress via popup to the user. I understand the mistake. I am closing this issue.

**Closed** 2021-04-06 20:04 UTC
Labels: feature-request, needs-approval

**Comment by pictos** [comment] 2021-04-06 21:47
@ArunPrakashG, thanks for bringing that up! And feel free to open any issue asking for features in the future :D

**Comment by IeuanWalker** [comment] 2021-04-06 22:24
@pictos @ArunPrakashG 
This sounds like what I'm looking for. 

Being able to use the popup control as a loading indicator/ overlay.

Currently, we are using [ACR.UserDialogs](https://github.com/aritchie/userdialogs/blob/95e121b17b9391728d2b8948ced4fa6b6637b949/src/Samples/Samples/ViewModels/ProgressViewModel.cs#L79), but as that control is no longer supported we are looking for a new solution.

Current code looks like this -

```csharp
using (this.Dialogs.Loading("Loading..")){
	// Do logic, i.e. load data from API, send data to API etc
}

```

Idea is the loading overlay appears when the logic beings and disappears when the logic finishes.

**Comment by pictos** [comment] 2021-04-06 22:26
@IeuanWalker extract that part of the code in another method wrapped by a try/finally block and calling the dismiss method doesn't solve the problem?

**Comment by IeuanWalker** [comment] 2021-04-06 22:38
@pictos Ye, just looks cleaner using a 'using' imo

**Comment by ArunPrakashG** [comment] 2021-04-07 05:55
> @pictos @ArunPrakashG
> This sounds like what I'm looking for.
> 
> Being able to use the popup control as a loading indicator/ overlay.
> 
> Currently, we are using [ACR.UserDialogs](https://github.com/aritchie/userdialogs/blob/95e121b17b9391728d2b8948ced4fa6b6637b949/src/Samples/Samples/ViewModels/ProgressViewModel.cs#L79), but as that control is no longer supported we are looking for a new solution.
> 
> Current code looks like this -
> 
> ```cs
> using (this.Dialogs.Loading("Loading..")){
> 	// Do logic, i.e. load data from API, send data to API etc
> }
> ```
> 
> Idea is the loading overlay appears when the logic beings and disappears when the logic finishes.

This is what i was trying to say as this is the same use case for me, To display activity to the user.
