### ISSUE TITLE
[Bug] Blank Pages in the Sample UWP App

### ISSUE THREAD

**Issue by goh-chunlin** [xamarin/XamarinCommunityToolkit#1043] opened 2021-03-07 03:40 UTC
### Steps to Reproduce

1. Clone the project to local machine;
2. Set UWP as the Startup Project;
3. Run;
4. Click on the Behaviors button;
5. The page is shown blank.

A detailed demo can be found on this video recording: https://youtu.be/CzxaT_GJiGg

As you can see in the video, the pages only displayed after the window is resized.

### Expected Behavior
The pages are shown successfully.

### Actual Behavior
The pages appear to be blank first and are only displayed correctly after the window is resized.

### Basic Information

- Version with issue: [Clone from this Commit](https://github.com/xamarin/XamarinCommunityToolkit/commit/caa3ebc71335d68e4a69758def542b322ccdbf90)
- Last known good version: N/A
- IDE: Visual Studio 2019 Professional Preview (16.10.0 Preview 10)
- Platform Target Frameworks: 
  - iOS:  N/A
  - Android: N/A
  - UWP:  **19041**
- Android Support Library Version: 
- Nuget Packages:
  - Xamarin.Essentials 1.5.3.2
  - Xamarin.Forms 5.0.0.1874 
  - Microsoft.NETCore.UniversalWindowsPlatform 6.2.10
- Affected Devices: Windows 10 20H2

### Workaround
As long as we comment out or remove the CollectionView.Footer used in App.xaml in Xamarin.CommunityToolkit.Sample project, as shown in the screenshot below, the problem will be fixed.
![image](https://user-images.githubusercontent.com/8535306/110228161-dea2b280-7f39-11eb-82eb-62cd1301f995.png)

### Reproduction imagery

![image](https://user-images.githubusercontent.com/8535306/110228137-b1560480-7f39-11eb-8e19-f8e83bd752a9.png)

### Reproduction Link

A detailed demo can be found on this video recording: https://youtu.be/CzxaT_GJiGg

**Comment by maxkoshevoi** [comment] 2021-03-13 21:53
Issue exists for both `develop` and `main` branches.

**Comment by Cfun1** [comment] 2021-03-13 22:04
@goh-chunlin thanks for reporting but I believe it is a duplicate of https://github.com/xamarin/XamarinCommunityToolkit/issues/606, it also includes the resizing of he window as a workaround in comments.
cc @AndreiMisiukevich @pictos

**Comment by pictos** [comment] 2021-03-13 22:13
@goh-chunlin this is a known issue and it's on Forms side. So I'm closing this one.

**Closed by pictos** 2021-03-13 22:13 UTC
Labels: bug, s/unverified
