### ISSUE TITLE
[Bug] LifecycleEffect Loaded event not firing on UWP

### ISSUE THREAD

**Issue by RubenDobbels** [xamarin/XamarinCommunityToolkit#1220] opened 2021-04-21 08:59 UTC
### Description
The LifecycleEffect does not seem to work on UWP outside of the sample app.
When tested on android it seems to work fine.
### Steps to Reproduce

1. Create an empty xamarin app
2. Add a lifecycle event to the MainPage xaml and bind the Loaded event
```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
             xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
             x:Class="App1.MainPage">
  <ContentPage.Effects>
    <xct:LifecycleEffect Loaded="LifecycleEffect_Loaded"/>
  </ContentPage.Effects>
  <StackLayout>
    <Label  Text="Start developing now" FontSize="Title" Padding="30,10,30,10">
      <Label.Effects>
        <xct:LifecycleEffect Loaded="LifecycleEffect_Loaded"/>
      </Label.Effects>
    </Label>
    <Label x:Name="lbl" FontSize="16" Padding="30,0,30,0"/>
  </StackLayout>
</ContentPage>
```

```
using System;

using Xamarin.Forms;

namespace App1
{
  public partial class MainPage : ContentPage
  {
    public MainPage()
    {
      InitializeComponent();
    }

    private void LifecycleEffect_Loaded(object sender, EventArgs e)
    {
      if (sender is Label)
        lbl.Text += "Label loaded \n";
      else if (sender is ContentPage)
        lbl.Text += "ContentPage loaded \n";
    }
  }
}
```

### Expected Behavior
The Loaded event gets fired.
### Actual Behavior
The loaded event does not get fire.
### Basic Information

- Version with issue: 1.1.0
- Last known good version:
- IDE: Visual Studio Enterprise 16.9.4
- Platform Target Frameworks: 
  - Android: 30
  - UWP:  19041 
- Nuget Packages: Xamarin.Forms 5.0.0.2012

### Reproduction Link
[LifecycleTest.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/6349503/LifecycleTest.zip)

**Comment by pictos** [comment] 2021-04-21 23:04
@RubenDobbels If you change your min target version to 2004 that solves your issue? Yeah, that isn't ideal and we are working to fix that, but I just want to make sure that his bug is caused by this detail.

**Comment by RubenDobbels** [comment] 2021-04-22 04:55
@pictos Changing the min target to 2004 does work indeed.

**Comment by AndreiMisiukevich** [comment] 2021-04-22 21:40
Same as #889 and #998
Closing this one since the reason is the same

**Closed by AndreiMisiukevich** 2021-04-22 21:40 UTC
Labels: bug, s/unverified

**Comment by sonic1015** [comment] 2022-07-27 21:32
Can we re-open this? I am getting this behavior when both my Min AND Max target are 2004 (19041).

Xamarin.CommunityToolkit: 2.0.4
Xamarin.Forms: 5.0.0.2478
UWP: 19041 (target & min)
IDE: VS 2022 17.2.6

If anyone knows a work-a-round though, please by all means.
