### ISSUE TITLE
[Enhacement] Better organization with a better usage of GitHub Projects board

### ISSUE THREAD

**Issue by Cfun1** [xamarin/XamarinCommunityToolkit#722] opened 2021-01-05 01:23 UTC
### Description
I am just opening this here to draw some attention and possibly avoid things get messy. By Keeping a proper tracking of issues with appropriate Labels and projects assignment, we will have a better overview of what is going on and where are we.

A reference would be [Xamarin.forms repo projects](https://github.com/xamarin/Xamarin.Forms/projects).

Some suggestions:

- [ ] Adding new Projects?
- [ ] Updating existing projects with old issues that are unassigned to any project.
- [ ] Configuring automation on Project for new issues (add to Triage for example).

**Comment by jfversluis** [comment] 2021-01-05 11:44
Hi @Cfun1 thank you for being so committed to our project.

That is definitely something I would like to do. I think the first priority though is getting everything ready for our v1. Since Forms 5 will lack a couple of things that have been moved to us, we need to be ready (and as stable as possible) when Forms 5 launches. This also means; having the Docs ready as much as possible, a blog post, some other content to help people transition, etc.

It might not be apparent to people outside of this project that this runs on a couple of volunteers. Javier and myself are attached from the Microsoft side, but also for us the work on this project happens mainly in our spare time. That is why sometimes we have some more time to spend, and sometimes not as much as we'd like to.

All of this is no excuse for not having our backlog in shape, but I just want to paint you a picture of the why and how things came to be. I hope you understand and any and all help is greatly appreciated. So if you have any concrete ideas about how we should arrange those project boards or which issue should have what label, please just comment, ping me and I'll make sure to add them. Also triaging issues and see if they are already fixed, are reproducible and what the cause might be would be very valuable. So if you are willing and able to contribute that way, please feel free to do so :)

In regard to this concrete issue: we are looking at the Forms and/or Essentials repo for inspiration on how to organize ourselves for sure. You will already recognize a lot from that. If we can make the action items in this issue a bit more concrete and form a plan on how to organize better, in fact: would it make sense to maybe open a discussion rather than an issue and see if we can gather some insights from different angles?

Thanks!

**Closed** 2021-01-05 16:52 UTC
Labels: housekeeping, proposal
