### ISSUE TITLE
Shell.Current.GoToAsync to xct:Popup restuls with error System.NullReferenceException

### ISSUE THREAD

**Issue by asafgo** [xamarin/XamarinCommunityToolkit#1469] opened 2021-07-05 06:34 UTC
### Description
I would like to display Popup with xamarin community toolkit Popup so but when trying to navigate to it using Shell I am receiving the error "System.NullReferenceException Message=Object reference not set to an instance of an object."
### Steps to Reproduce

Popup XAML Code and Code behind

`     <?xml version="1.0" encoding="utf-8" ?>
     <xct:Popup xmlns="http://xamarin.com/schemas/2014/forms"
                  xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                  xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
                  x:Class="Restuco_Tables.Views.AddAreaPopup"
                Shell.PresentationMode="ModalAnimated"
                  Size="300, 300"
                  >
        
         <StackLayout>
             <Label Text="This is a Popup!" VerticalOptions="CenterAndExpand" HorizontalOptions="CenterAndExpand"/>
         </StackLayout>
            
     </xct:Popup>
     [XamlCompilation(XamlCompilationOptions.Compile)]
         public partial class AddAreaPopup : Popup
         {
             public AddAreaPopup()
             {
                 InitializeComponent();
             }
         }

`

registered Routing in AppShell

`Routing.RegisterRoute(nameof(AddAreaPopup), typeof(AddAreaPopup));`

call to the Popup using Shell

`     private async void tbiNewArea_Clicked(object sender, EventArgs e)
     {
         await Shell.Current.GoToAsync("/AddAreaPopup");
     }`

### Actual Behavior
"System.NullReferenceException Message=Object reference not set to an instance of an object."
### Basic Information

- Version with issue: 1.2.0
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  14.20.0.24
  - Android: 11..3.0.4
  - UWP:

**Comment by Cfun1** [comment] 2021-07-05 07:53
This is not a bug

> Who guaranteed that Popup could be cast to ShellNavigationState which is the type of the expected parameter of GoToAsync() ?
 https://stackoverflow.com/q/68234488/5228202

**Comment by jfversluis** [comment] 2021-07-05 08:10
At this time Popup is not supported on Shell. We might want to put in an issue to see if there's any interest in that and if we can even do that. Closing this one for now.

**Closed by jfversluis** 2021-07-05 08:10 UTC
Labels: bug, s/unverified
