### ISSUE TITLE
[Bug] SnackBarOptions.Actions has getter only

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/XamarinCommunityToolkit#474] opened 2020-10-21 07:58 UTC
Makes it cumbersome to init these as one has to use the constructor and provide all the parameters just to set some actions.
Actions should have a setter also.

**Comment by VladislavAntonyuk** [comment] 2020-10-22 04:30
We like immutability. Use ctor

**Comment by Tommigun1980** [comment] 2020-10-22 12:24
> We like immutability. Use ctor

Eh. I won't. It's so much clearer to chain construction such as
```c#
new A()
{
   1, 3 4,
   new B()
   {
      1, 2, 3
   }
}
```

etc, than to send in everything via constructors. Why would an entire API disregard a common pattern just because someone doesn't like it? Also, every other property has a setter than Actions, why is it special?

**Comment by Tommigun1980** [comment] 2020-10-22 12:30
> We like immutability. Use ctor

Well that's awfully smug. I won't. It's so much clearer to chain construction such as

```c#
new Something()
{
   A = 1,
   B = new SomethingElse()
   {
      D = 1,
      E = 2,
      F = new List<int>()
      {
         1, 2, 3
      }
   }
}
```

etc, than to send in everything via constructors. Why would an entire API disregard a common pattern just because someone doesn't like it? Also, every other property has a setter than Actions, why is it special?

**Comment by jfversluis** [comment] 2020-10-22 12:39
I don't know who "we" is in this case, but as far as I am concerned everything can be discussed :) Not sure if this is a bug though. Technically it works as intended atm

Does adding a setter make for any side-effects as far as we can tell right now?

**Comment by Tommigun1980** [comment] 2020-10-22 12:40
> I don't know who "we" is in this case, but as far as I am concerned everything can be discussed :) Not sure if this is a bug though. Technically it works as intended atm
> 
> Does adding a setter make for any side-effects as far as we can tell right now?

Well you are right, maybe it's a feature request then. I thought it was a bug because other properties in the same class has setters except Actions, so it looked like a bug to me.

**Comment by Tommigun1980** [comment] 2020-10-27 02:13
Any chance this could get corrected at some point? Construction of SnackBar is quite ugly atm as some objects (MessageOptions) the constructor requires has setters only, so you are forced to combine all kinds of different initialisation styles. Instead of being able to chain everything as in the OP, one has to chain SOME of the objects and ultimately send them in to the constructor, as its Actions property does not have a setter. Everything else has setters and some don't even have constructor arguments so it really is a special case.

Also, if you are adamant about having constructors only you will need to remove the properties from for example MessageOptions and add constructor arguments to it, but in that case I think a pattern such as ACL's
```c#
                            var toastConfig = new ToastConfig()
                                .SetAction(action => action
                                    .SetText("Open Chat")
                                    .SetAction(async () =>
                                    {
                                        if (!this.vm.GetCancellationToken().IsCancellationRequested)
                                            await this.OpenChat(args.ChatRoom.Id);
                                    }));
```
would be better. But easiest would be to just expose Actions imho and be done with it.

**Comment by Tommigun1980** [comment] 2020-10-27 02:25
This is how you currently have to create the options object:

```c#
                            var toastConfig = new SnackBarOptions(
                                new MessageOptions()
                                {
                                    Message = $"{toastVm.UserProfile.FirstName} in #{toastVm.ActivityType.Tag}: {args.ChatMessage.Message}"
                                },
                                2000, Color.Red, false, new SnackBarActionOptions[]
                                {
                                    new SnackBarActionOptions()
                                    {
                                        Text = "Open Chat",
                                        Action = async () =>
                                        {
                                            if (!this.vm.GetCancellationToken().IsCancellationRequested)
                                                await this.OpenChat(args.ChatRoom.Id);
                                        }
                                    }
                                });
```

What I'd prefer:
                        var toastConfig = new SnackBarOptions()
                            {
                                MessageOptions = new MessageOptions()
                                {
                                    Message = $"{toastVm.UserProfile.FirstName} in #{toastVm.ActivityType.Tag}: {args.ChatMessage.Message}"
                                },
                                Actions = new SnackBarActionOptions[]
                                {
                                    new SnackBarActionOptions()
                                    {
                                        Text = "Open Chat",
                                        Action = async () =>
                                        {
                                            if (!this.vm.GetCancellationToken().IsCancellationRequested)
                                                await this.OpenChat(args.ChatRoom.Id);
                                        }
                                    }
                                },
                                // preferably these should be optional, and SnackBar could be themed in one place as suggested at https://github.com/xamarin/XamarinCommunityToolkit/issues/477
                                BackgroundColor = Color.Red,
                                Duration = 2000
                            };

Apparently the other things in SnackBarOptions don't have setters either so I was mistaken it only being Actions lacking it. The inner objects, like MessageOptions and SnackBarActionOptions, do have setters but no constructor arguments.

**Comment by VladislavAntonyuk** [comment] 2020-10-28 19:08
in progress

**Comment by AndreiMisiukevich** [comment] 2020-11-17 12:38
Fixed in https://github.com/xamarin/XamarinCommunityToolkit/pull/508

**Closed by AndreiMisiukevich** 2020-11-17 12:38 UTC
Labels: a/Snackbar, feature-request, in-progress, needs-approval
