### ISSUE TITLE
[Enhancement] Entry Arrow Color

### ISSUE THREAD

**Issue by Saleh-Software** [xamarin/XamarinCommunityToolkit#1229] opened 2021-04-24 04:33 UTC
Hello Xamarin Toolkit

There is Any Effect or anything about change Entry Arrow Color?
![Capture](https://user-images.githubusercontent.com/48956033/115947277-e57e8800-a4db-11eb-93b5-9062c010464e.PNG)

**Comment by Cfun1** [comment] 2021-04-24 10:32
Duplicate of #735?

**Comment by pictos** [comment] 2021-04-24 17:31
@Saleh-Software, not sure if you asking if we have this feature on this project or if there's a way to do it. So I'll answer both.

We don't have this feature implemented yet. There's a way to change the cursor color using the platform-specific APIs, on Android you can do it on `styles.xml` and I don't know how to do it on iOS.

**Comment by pictos** [comment] 2021-04-24 17:32
Closing this issue because is 
Duplicate of #735

**Closed by pictos** 2021-04-24 17:32 UTC
Labels: feature-request, needs-approval
