### ISSUE TITLE
About xamarin playing m3u8 video.

### ISSUE THREAD

**Issue by bbhxwl** [xamarin/XamarinCommunityToolkit#1620] opened 2021-09-17 03:22 UTC
Libvlcsharp can play m3u8, but some MP4 will get stuck. It's good to play MP4 with MediaElement, but m3u8 can't be played. Can anyone let MediaElement play m3u8 or libvlcsharp play specific MP4 without getting stuck?

I play some specific videos, using computer players, and browsers, but there is no problem, but using libvlc will freeze. And every time I went to the place where it was stuck, it happened 100% of the time.

https://code.videolan.org/videolan/LibVLCSharp/-/issues/505

**Comment by vhugogarcia** [comment] 2021-09-21 22:09
@bbhxwl I recommend you for live streaming applications to use https://github.com/Baseflow/XamarinMediaManager, due to it provides the best video player on Android and the native for each platform on iOS. 

Xamarin community toolkit has a media manager for the basic only, which is awesome if you want to create a store app where you have previews (VoD) of certain products, etc. 

BaseFlow media manager is also built by the community and it is free to use.

**Comment by jfversluis** [comment] 2021-09-29 13:29
The linked media manager is indeed pretty epic :) I hope we get our MediaElement up to par at some point in the future. For now this is a duplicate of #404 

Thanks for the suggestion @bbhxwl and helping out @vhugogarcia

**Closed by jfversluis** 2021-09-29 13:29 UTC
Labels: feature-request, needs-approval
