### ISSUE TITLE
[Bug MauiCompat] Popup can't open in Maui Application!

### ISSUE THREAD

**Issue by thaihuydang** [xamarin/XamarinCommunityToolkit#1750] opened 2021-11-30 22:12 UTC
### Description

I use Xamarin community toolkit MauiCompat to implement popup for .net Maui but when I call to open the popup, it had an error  like the image below 
![image](https://user-images.githubusercontent.com/17990989/144109992-bb747b32-4f82-411e-8f1f-6c35263375a7.png)

### Stack Trace

     at Xamarin.CommunityToolkit.Helpers.XCT.get_Context()
   at Xamarin.CommunityToolkit.Extensions.NavigationExtensions.PlatformShowPopup(BasePopup popup)
   at Xamarin.CommunityToolkit.Extensions.NavigationExtensions.ShowPopup(INavigation navigation, BasePopup popup)
   at MauiApp4.MainPage.OnCounterClicked(Object sender, EventArgs e) in C:\Users\thaih\source\repos\MauiApp4\MauiApp4\MainPage.xaml.cs:line 19
   at Microsoft.Maui.Controls.Button.Microsoft.Maui.Controls.Internals.IButtonElement.PropagateUpClicked() in D:\a\1\s\src\Controls\src\Core\Button.cs:line 164
   at Microsoft.Maui.Controls.ButtonElement.ElementClicked(VisualElement visualElement, IButtonElement ButtonElementManager) in D:\a\1\s\src\Controls\src\Core\ButtonElement.cs:line 61
   at Microsoft.Maui.Controls.Button.SendClicked() in D:\a\1\s\src\Controls\src\Core\Button.cs:line 150
   at Microsoft.Maui.Controls.Button.Microsoft.Maui.IButton.Clicked() in D:\a\1\s\src\Controls\src\Core\HandlerImpl\Button\Button.Impl.cs:line 9
   at Microsoft.Maui.Handlers.ButtonHandler.OnClick(IButton button, View v) in D:\a\1\s\src\Core\src\Handlers\Button\ButtonHandler.Android.cs:line 190
   at Microsoft.Maui.Handlers.ButtonHandler.ButtonClickListener.OnClick(View v) in D:\a\1\s\src\Core\src\Handlers\Button\ButtonHandler.Android.cs:line 199
   at Android.Views.View.IOnClickListenerInvoker.n_OnClick_Landroid_view_View_(IntPtr jnienv, IntPtr native__this, IntPtr native_v) in /Users/builder/azdo/_work/2/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-31/mcw/Android.Views.View.cs:line 2456
### Link to Reproduction Sample

https://github.com/thaihuydang/Popup.git
### Steps to Reproduce

1. run the application
2. click on the Click me button
3. 

### Basic Information

- Version with issue: 1.3.0-compat-alpha3
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by rezo12** [comment] 2021-12-01 19:05
I am getting the same issue
![image](https://user-images.githubusercontent.com/33411469/144297430-13b11f9e-6286-4dde-822e-c9059bd86d47.png)

**Comment by rezo12** [comment] 2021-12-02 15:14
I looked further into this and got past this error when creating a simple shell renderer, because my main page is a AppShell.
![image](https://user-images.githubusercontent.com/33411469/144448607-ce8e788e-7be8-460c-8d3a-93f648ca6d75.png)
I then registered it in the startup:
![image](https://user-images.githubusercontent.com/33411469/144448803-858bca06-3efb-439b-995b-4ebbf8c04c78.png)

Now I am getting the following error:
![image](https://user-images.githubusercontent.com/33411469/144449091-bdaeca98-7f49-4fc7-9e29-9f9a318730d1.png)

This is because the because the BasePopup is of type VisualElement and not View I believe

**Comment by VladislavAntonyuk** [comment] 2021-12-03 15:48
@thaihuydang Could you please attach a small app to reproduce?

I created a small sample and reproduced it, but that is because I used ContentPage with handler architecture.
If I switch to Renderer implementation, I receive NRE in MAUI (during renderer creation).

**Comment by VladislavAntonyuk** [comment] 2021-12-03 16:13
@thaihuydang it is an expected error. The app tries to receive Page renderer (Application.Current.MainPage.GetRenderer()), but it is not registered.
also, it is not a scenario where MauiCompat should be used. MaiCompat is for apps with custom controls and renderers. it won't work if you use it with Handler architecture.
Please use CommunityToolkit.Maui. (But Popup implementation is in progress). You should either use custom control or wait till Popup is migrated to Maui CommunityToolkit

**Comment by thaihuydang** [comment] 2021-12-04 06:41
@VladislavAntonyuk thank you reply. I will happy to use Maui Community Toolkit when it included Popup.

**Comment by VladislavAntonyuk** [comment] 2022-03-23 19:43
@thaihuydang You can use popup from CommunityToolkit.Maui.

**Comment by VladislavAntonyuk** [comment] 2022-05-31 06:42
As we released MCT with Popup I am closing this issue.

**Closed** 2022-05-31 06:42 UTC
Labels: bug, maui-compat
