### ISSUE TITLE
[Bug] LongPressCommand not working in UWP

### ISSUE THREAD

**Issue by nacompllo** [xamarin/XamarinCommunityToolkit#1288] opened 2021-05-13 10:51 UTC
### Description
The LongPressCommand does not work in UWP, however on Android, iOS and macOS it works correctly.

### Steps to Reproduce

1. Add LongPressCommand in some control and bind the property to a command in the view model, it works on Android, iOS, and macOS but not UWP.
```
<Label Text="Long click"
            TextColor="Black"                                  
            FontSize="Small"
            xct:TouchEffect.LongPressCommand="{Binding TestCommand}"
            xct:TouchEffect.LongPressDuration="900"/>
```

### Expected Behavior
When the user makes a long click on the control, the binded command should be executed.

### Actual Behavior
When you hold down a control the time defined in LongPressDuration in UWP nothing happens.

### Basic Information

- Version with issue: 1.2.0-pre1
- Last known good version: 1.0.3
- IDE: Visual Studio Community 2019 (16.9.5)
- Platform Target Frameworks: 
  - UWP:  
**Target version: 1903
Min version: 1809**
- Nuget Packages: Xamarin.CommunityToolkit 1.2.0-pre1
- Affected Devices: All UWP devices.

**Comment by AndreiMisiukevich** [comment] 2021-05-13 22:43
Hi @nacompllo thanks for the report
Does regular Command work?

if not, then try to add

```csharp
var assembliesToInclude = new List<Assembly>()
{
    typeof(Xamarin.CommunityToolkit.Effects.TouchEffect).GetTypeInfo().Assembly
};

Xamarin.Forms.Forms.Init(e, assembliesToInclude);
```

to your UWP code

**Comment by nacompllo** [comment] 2021-05-14 07:17
> Hi @nacompllo thanks for the report
> Does regular Command work?
> 
> if not, then try to add
> 
> ```cs
> var assembliesToInclude = new List<Assembly>()
> {
>     typeof(Xamarin.CommunityToolkit.Effects.TouchEffect).GetTypeInfo().Assembly
> };
> 
> Xamarin.Forms.Forms.Init(e, assembliesToInclude);
> ```
> 
> to your UWP code

Hi, the normal command doesn't work in UWP either, not even if I include the assemblies in App.xaml.cs.

**Comment by themronion** [comment] 2021-05-15 10:09
@nacompllo play with the minimum/target version. There was a problem with that, i don't remember exactly what versions are needed, @AndreiMisiukevich remind please

**Comment by nacompllo** [comment] 2021-05-15 10:49
> @nacompllo play with the minimum/target version. There was a problem with that, i don't remember exactly what versions are needed, @AndreiMisiukevich remind please

I have tried several combinations but it seems that it does not work either, at the moment the only solution is to stay in version 1.0.3 which is the last version where it works.

**Comment by AndreiMisiukevich** [comment] 2021-05-15 23:30
@jfversluis @pictos  what is the minimum required version for UWP?

**Comment by AndreiMisiukevich** [comment] 2021-05-15 23:33
Try to set UWP higher UWP version like described here https://github.com/xamarin/XamarinCommunityToolkit/pull/1247

I am pretty sure it's not TouchEffect issue (just need to set a proper UWP version)

**Comment by pictos** [comment] 2021-05-15 23:36
@AndreiMisiukevich if the issue is the caused by UWP version, that should be fixed in the next stable release.

**Comment by AndreiMisiukevich** [comment] 2021-05-15 23:38
Can anyone check if toucheffect works fine on UWP with our sample app?

**Comment by pictos** [comment] 2021-05-15 23:44
@AndreiMisiukevich yes it's working.

**Comment by AndreiMisiukevich** [comment] 2021-05-15 23:54
@pictos can we advice some workaround for now and close this issue?

**Comment by pictos** [comment] 2021-05-15 23:57
@AndreiMisiukevich may be saying that this is duplicated from #998 or any other UWP target issue and close this one... 

IMHO we can close this one since we have other issues tracking this problem.

**Comment by AndreiMisiukevich** [comment] 2021-05-16 00:00
> @AndreiMisiukevich if the issue is the caused by UWP version, that should be fixed in the next stable release.

**Closed by AndreiMisiukevich** 2021-05-16 00:00 UTC
Labels: UWP, a/TouchEffect, bug, s/unverified
