### ISSUE TITLE
[Bug] StateLayout: Collection was modified

### ISSUE THREAD

**Issue by Axemasta** [xamarin/XamarinCommunityToolkit#784] opened 2021-01-19 21:48 UTC
### Description

I thought I'd use `StateLayout` in a tutorial page, the first time you see the page it shows some information, every subsequent load you dont see the info. This page is my root of my `FlyoutPage`, if you navigate to a page you leave it, if you deselect that page you go back to this page (its a background page).

When navigating back to this page after changing my code over from a `IsVisible="{Binding ShowTutorial}"` pattern, I noticed I was getting the following crash:

```
  at System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () [0x00013] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:1163 
  at System.Collections.Generic.List`1+Enumerator[T].MoveNext () [0x0004a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:1156 
  at System.Linq.Enumerable+WhereEnumerableIterator`1[TSource].MoveNext () [0x0004e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/System.Linq/src/System/Linq/Where.cs:140 
  at System.Linq.Enumerable+<OfTypeIterator>d__32`1[TResult].MoveNext () [0x00067] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/System.Linq/src/System/Linq/Cast.cs:24 
  at System.Linq.Enumerable+SelectIListIterator`2[TSource,TResult].MoveNext () [0x00029] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/System.Linq/src/System/Linq/Select.cs:487 
  at System.Threading.Tasks.Task.WhenAll[TResult] (System.Collections.Generic.IEnumerable`1[T] tasks) [0x000ba] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:5657 
  at Xamarin.CommunityToolkit.UI.Views.StateLayoutController.ChildrenFadeTo (Xamarin.Forms.Layout`1[T] layout, System.Boolean animate, System.Boolean isHide) [0x000ae] in <fa8f5d76b92c43368c40cb2294002440>:0 
  at Xamarin.CommunityToolkit.UI.Views.StateLayoutController.SwitchToContent (System.Boolean animate) [0x00098] in <fa8f5d76b92c43368c40cb2294002440>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 
  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.8.0.3/src/Xamarin.iOS/Foundation/NSAction.cs:178 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.8.0.3/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.8.0.3/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at Senso.Client.Mobile.iOS.Application.Main (System.String[] args) [0x00001] in /Users/***********/MyApp/Main.cs:17 
```

I don't have a suitable reproduction because but that is a crash coming from this framework so I thought I'd report it now!

**Comment by AndreiMisiukevich** [comment] 2021-01-20 23:22
@Axemasta can you validate the fix from https://github.com/xamarin/XamarinCommunityToolkit/pull/787

**Comment by jfversluis** [comment] 2021-01-21 10:18
You can download a nupkg with this fix from [here](https://dev.azure.com/xamarin/_apis/resources/Containers/8941246/nuget?itemPath=nuget%2FXamarin.CommunityToolkit.1.0.0-preview2909.nupkg) :)

**Comment by Axemasta** [comment] 2021-01-21 10:24
Let me give it a go, I'll have to do it in a sample because the app with the crash is not on form 5.0 😅

**Comment by jfversluis** [comment] 2021-01-21 10:25
Hold on... Not on Forms 5? Then what packages and versions are you using exactly? There is no (stable) Toolkit version that is not using Forms 5

**Comment by Axemasta** [comment] 2021-01-21 10:26
Forms 4.8.0.1821 & Community Toolkit 1.0.0-pre5

**Comment by Axemasta** [comment] 2021-01-21 10:27
I'm not planning on updating to Forms 5 until Prism has a stable release 😁

**Comment by jfversluis** [comment] 2021-01-21 10:31
Ah OK, understandable, but that is a good thing to mention in your next bug report then :) 

Because this might have all kinds of causes then: maybe Prism, maybe Forms 4.8, maybe Toolkit. Again, I understand your position, but I hope you'll also understand this is not something we can fix if we don't know this is happening in the latest bits of our code as well. Maybe this is something that is already fixed and we're now about to implement code that potentially changes other things or even breaks something while there was no issue to begin with.

If there is a way to verify this with the latest stable release (1.0.2) and can confirm this is still happening that would be great. Else I'm inclined to close this one for now until we can

**Comment by Axemasta** [comment] 2021-01-21 11:46
Sure the crash itself is coming from the toolkit:
```
  at Xamarin.CommunityToolkit.UI.Views.StateLayoutController.ChildrenFadeTo (Xamarin.Forms.Layout`1[T] layout, System.Boolean animate, System.Boolean isHide) [0x000ae] in <fa8f5d76b92c43368c40cb2294002440>:0 
  at Xamarin.CommunityToolkit.UI.Views.StateLayoutController.SwitchToContent (System.Boolean animate) [0x00098] in <fa8f5d76b92c43368c40cb2294002440>:0 
```

But i think im going to have to make the reproduction with prism included since I can't replicate with purely vanilla forms. I imagine how prism is holding onto references of the detail pages is partly what is causing the issue!

**Comment by jfversluis** [comment] 2021-01-21 11:51
Not looking to put the blame on someone else in this case. It might as well be us. 

But this is why the template is pretty important. The version numbers, other products involved and reproduction showing all that can be very important not just for us, but also for yourself to be able to identify the root cause. There might still be something for us (or the other products) to fix, but at the very least you might find a way to unblock yourself and provide us with a reproduction that will help us get to the cause and fix faster.

Anyway, please let us know what you find! :)

**Comment by Axemasta** [comment] 2021-01-27 11:00
@AndreiMisiukevich Can confirm this issue is not happing in the latest versions of all packages (XCT 1.0.3, XF 5.0.0.1931) 😄

I'm happy to close this issue if thats alright with everyone

**Closed** 2021-01-27 20:56 UTC
Labels: a/StateLayout, bug, s/unverified

**Comment by ValonK** [comment] 2021-02-11 09:12
> You can download a nupkg with this fix from [here](https://dev.azure.com/xamarin/_apis/resources/Containers/8941246/nuget?itemPath=nuget%2FXamarin.CommunityToolkit.1.0.0-preview2909.nupkg) :)

Can you post the Fix again?

**Comment by Axemasta** [comment] 2021-02-11 09:14
@ValonK I was able to verify the fix on the latest publicly available version of the toolkit, is your app using the latest version?

**Comment by ValonK** [comment] 2021-02-11 09:16
@Axemasta yes I'm using the latest version 1.0.2

**Comment by Axemasta** [comment] 2021-02-11 09:17
Have you been able to reproduce the issue in a separate project?

**Comment by ValonK** [comment] 2021-02-11 09:19
> Have you been able to reproduce the issue in a separate project?

I will try to reproduce it, thx

**Comment by AndreiMisiukevich** [comment] 2021-02-15 00:55
Or maybe we should merge my fix as well https://github.com/xamarin/XamarinCommunityToolkit/pull/787
