### ISSUE TITLE
[Bug] [iOS] TouchEffect triggers the command after we start scrolling

### ISSUE THREAD

**Issue by taenito** [xamarin/XamarinCommunityToolkit#1506] opened 2021-07-13 13:19 UTC
### Description

[iOS] TouchEffect triggers the command even if the user has started scrolling
Tried with ListView and ScrollView

[Android] the command is not triggered and le view continues to scroll (expected behavior)

### Steps to Reproduce

1. Touch start
2. Scroll (quickly)
3. Touch stop

### Expected Behavior

Like Android, do not trigger the command and continue to scroll

### Actual Behavior

iOS stop scrolling and triggers the command

### Basic Information

- Version with issue: 1.3.0-pre1
- Platform Target Frameworks:
  - iOS:  11

### Reproduction imagery

https://user-images.githubusercontent.com/6932633/125453142-475d574d-c0ce-45b2-8710-7d205aad737c.mp4

**Comment by AndreiMisiukevich** [comment] 2021-07-13 19:22
Duplicate of https://github.com/xamarin/XamarinCommunityToolkit/issues/1261

**Closed by AndreiMisiukevich** 2021-07-13 19:22 UTC
Labels: bug, s/unverified
