### ISSUE TITLE
[Bug] [CameraView] [iOS] Flash does not work

### ISSUE THREAD

**Issue by joehanna** [xamarin/XamarinCommunityToolkit#747] opened 2021-01-11 10:53 UTC
### Description

On iOS the CameraView does not trigger a flashlight even though Flash is on.

This is similar in nature to https://github.com/xamarin/XamarinCommunityToolkit/issues/301

### Steps to Reproduce

1. Add a CameraView to a page.
2. Set FlashMode to On in XAML
3. Run and trigger shutter

### Expected Behavior

The flash light works.

### Actual Behavior

The flash light does not work.

### Basic Information

- Nuget library 1.0.0
- Last known good version: Unknown
- IDE: VS Mac 8.8.4 (build 30)
- Platform Target Frameworks: 
  - iOS:  14.3
- Affected Devices: Tested on iPhone 6 & iPhone 12

NOTE: My app uses Xamarin.iOS with Xamarin.Forms Embedding. 

### Workaround
None that I know of.

I tried to download the CommunityToolkit Sample to see if it worked in there but I couldn't even get it to build and run due to dependencies.  I saw Gerald Versluis got it to work Twitch video on YouTube https://www.youtube.com/watch?v=-oSlzuTbU30 but everything I try doesnt work.

**Comment by SJaschinski** [comment] 2021-07-22 20:08
Have the exact same issue here. So, I can confirm the described behaviour. iOS version is 14.6 and XCT version is 1.2.0 on my end. Flash is not working neither in FlashMode On, Auto nor Torch.

**Comment by jfversluis** [comment] 2021-08-09 14:12
Briefly looked into it. The strange thing is it works in the sample app without any problem. When doing it in a standalone app, not so much. For some reason I was triggered to set the flash only when the camera went into the available state and that seems to work!

Weird enough when you try to set it after that the flash will stop working again. Not sure why that is. Anyway, see a reproduction project attached that triggers the flash each time. Hope this is helpful while we investigate a proper fix.

[Repro747.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/6955056/Repro747.zip)

**Comment by jfversluis** [comment] 2021-08-09 21:05
Could you please install [this NuGet](https://1drv.ms/u/s!Anrk6U9nRknzg6Ii6HHXwjUzlh5UNg?e=emVOFg) on your project and verify that it fixes the issue?

**Comment by SJaschinski** [comment] 2021-08-10 12:26
Hi @jfversluis, thanks for looking into the issue. I was able to test the given NuGet package in my solution. I can confirm that this version fixes the issue for FlashMode Auto and On. When I try FlashMode Torch this raises an unhandled exception as soon as the Shutter method is called: 

![2021-08-10_14-18-07](https://user-images.githubusercontent.com/21976529/128865967-3e71f8d6-35cf-443f-9b0b-0fccc433348d.jpg)

In my case I want to use FlashMode Auto. So, this fix would already do the job. But still wanted to let you know that there still seems to be a problem. Please keep the great work up regarding XCT! If you want me to do any further tests please let me know...

**Comment by jfversluis** [comment] 2021-08-10 13:47
Yes! That was kind of what I was expecting while looking into this further.

Please try [this new package](https://1drv.ms/u/s!Anrk6U9nRknzg6IjRCgvWoIXyzev9w?e=f3nysF) that should work for all scenarios, also when switching between modes at runtime. Let me know how that goes!

**Comment by SJaschinski** [comment] 2021-08-13 15:33
Hey @jfversluis, using the new package you provided all is up and running. Also integrated an additional option into our app to toggle flash modes at runtime which works as well. So, first of all thanks for the fix and also thanks for the inspiration to further enhance our app. When do you think this will be merged into the main branch?

**Comment by jfversluis** [comment] 2021-08-13 17:55
Thanks for letting me know! Merging this now there should be a new pre-release with this fix soon :)

**Closed** 2021-08-13 17:55 UTC
Labels: bug, p/iOS, a/CameraView :camera_flash:
