### ISSUE TITLE
[Proposal] SegmentedControl

### ISSUE THREAD

**Issue by bartlannoeye** [xamarin/XamarinCommunityToolkit#7] opened 2017-02-16 14:36 UTC
_From @jamesmontemagno on December 23, 2016 7:13_

Coming soon

_Copied from original issue: FormsCommunityToolkit/Controls#4_

**Comment by wcoder** [comment] 2017-10-30 19:45
Maybe it is what you mean?

Segmented Control Plugin for Xamarin Forms
https://github.com/alexrainman/SegmentedControl

**Comment by pauldipietro** [comment] 2018-04-18 00:35
This needs some clarification.

**Comment by jfversluis** [comment] 2020-05-29 10:07
Assuming this is still something people/we might want to add so keeping it here for reference

**Comment by SunnyMukherjee** [comment] 2020-06-15 15:44
Adding here for future reference

https://github.com/CrossGeeks/SegmentedControlSample
https://github.com/CrossGeeks/ExtendedSegmentedTabControl

**Comment by roubachof** [comment] 2020-06-27 21:56
I thing @jsuarezruiz is working on `TabView` (I saw amazing specs some weeks ago). Maybe we should just wait for the XF implementation.

**Comment by SunnyMukherjee** [comment] 2020-06-30 02:03
@roubachof Thanks.  I saw this too recently.  I'm wondering if it will be released in the first release of MAUI.

**Comment by jamesmontemagno** [comment] 2020-07-01 22:32
I am not sure if TabView is the same as segmented control. I look at it more as options that are used to filter the content and not necessarily show different things, but could........ so if you define the control to be just the segmented control and the user has control of what to do, then it is a bit different.

**Comment by jsuarezruiz** [comment] 2020-07-06 12:13
Using styles, etc. we can get something like a SegmentControl using `TabView`. But, we can discuss about necessary functionality and options to include in TabView to cover both cases.

**Comment by hnabbasi** [comment] 2020-10-07 03:55
This is great. I opened a issue #385 for the Segment control I am migrating from Xamarin.Forms to this toolkit.

**Comment by jfversluis** [comment] 2020-10-08 19:17
Duplicate of #385 let's discuss further there

**Closed by jfversluis** 2020-10-08 19:17 UTC
Labels: proposal
