### ISSUE TITLE
cameraView.Shutter(); Is not working on IOS on latest package(1.0.3 and 1.1.0)

### ISSUE THREAD

**Issue by singhavinash108** [xamarin/XamarinCommunityToolkit#1150] opened 2021-03-30 12:43 UTC
cameraView.Shutter(); Is not working on IOS on latest package(1.0.3 and 1.1.0)

**Comment by GUOLDEV** [comment] 2021-03-30 19:55
Hi @singhavinash108, I believe the issue reported was already fixed in this [PR](https://github.com/xamarin/XamarinCommunityToolkit/pull/1119).

**Comment by pictos** [comment] 2021-04-06 01:33
@singhavinash108 Can you try our nightly build and see if it fixed your issue?

**Comment by singhavinash108** [comment] 2021-04-06 18:10
@pictos ok, i will try, but is there any ETA for latest version? just asking because i need to deliver the functionality.

**Comment by pictos** [comment] 2021-04-06 18:47
@singhavinash108, since that PR was merged into main branch, we should have a new release in a couple weeks

**Comment by haavamoa** [comment] 2021-04-07 09:38
@pictos I don't see a 1.1.1-pre version out on Nuget.org. [Also the PR you linked to failed it's builds.](https://dev.azure.com/xamarin/public/_build/results?buildId=38077&view=results) How can we download and see if it resolved the issue? @jfversluis

**Comment by pictos** [comment] 2021-04-07 17:44
@haavamoa can you try this one?
https://dev.azure.com/xamarin/6fd3d886-57a5-4e31-8db7-52a1b47c07a8/_apis/build/builds/38378/artifacts?artifactName=nuget&api-version=6.0&%24format=zip

**Comment by singhavinash108** [comment] 2021-04-09 02:53
Getting incorrect  rotation value on samsung s21

**Comment by matteovelati** [comment] 2021-05-18 20:28
Where can we find 1.1.1 that solves this issue?

**Comment by GUOLDEV** [comment] 2021-05-18 21:36
Hi @matteovelati, you can find the fixed version in the latest preview version [here](https://github.com/xamarin/XamarinCommunityToolkit/releases/tag/1.2.0-pre2)

**Comment by jfversluis** [comment] 2021-08-17 07:05
Not much info on this issue, I'm going t assume this is fixed with the latest changes, if not, please open a new issue with more details and a reproduction

**Closed by jfversluis** 2021-08-17 07:05 UTC
Labels: need-more-information
