### ISSUE TITLE
Overlay Control 

### ISSUE THREAD

**Issue by sarthak1995-26** [xamarin/XamarinCommunityToolkit#671] opened 2020-11-28 17:12 UTC
Overlay control can be a content view which can be open at any position above any view on content page without losing focus of a current focused control(e.g Entry).

Now many people will say you can do that using Rg.Plugin.Popup but what you will found that if you open a popup having any entry focused you will see keyboard will closed and entry fill lose it's focused state as soon as popup opens.

Where as Overlay will not cause losing focus state of any focused control while Overlay being open or closed

It will be a very similar to a **Overlay widget** Flutter framework has

For more explanation  see

https://medium.com/saugo360/https-medium-com-saugo360-flutter-using-overlay-to-display-floating-widgets-2e6d0e8decb9

Since it will be a content view any one can customise it's content easily.

This will allows us to create ComboBox,Custom Dropdown picker , Autocomplete control etc

## API Changes
It will be a standalone new control

## Intended Use Case
We can use this control to create :-
Combobox
Autocomplete

**Comment by VladislavAntonyuk** [comment] 2020-12-13 00:44
I think it should be an enhancement for existing PopupControl.

**Comment by sarthak1995-26** [comment] 2020-12-13 09:43
@martijn00 Is this possible for Rg Popup Somehow ?

**Comment by sarthak1995-26** [comment] 2020-12-13 09:44
Closing this since it might not possible to have a separate popup control in toolkit for this

**Comment by ahoefling** [comment] 2020-12-13 14:29
This is a great idea in app development especially for internal or pre-production scenarios. It won't work with the current popup specification as each platform handles popups very differently. For example, this could work with the Dialog (Android) and Popover (iOS) but not the Flyout (UWP). That is because the Flyout dismisses when clicked outside or to a different screen. As of right now you can't change that behavior. Once we add support for other platforms such as GTK# and Tizen I think support will get even more complex for the Popup Control.

There are already techniques for rendering overlays in Xamarin.Forms and they have been part of the core platform since the Grid control.

```xml
<Grid>
    <StackLayout>
        <!-- all content goes here -->
    </StackLayout>
    <Grid
        VerticalOptions="StartAndExpand"
        HorizontalOptions="EndAndExpand">
        <!-- draw content for overlay here -->
    </Grid>
<Grid/>
```

If this technique doesn't solve your problem could you provide a sample usage to help understand what you are thinking. 

I'm not saying no or this is not right for XCT, I just don't think it is a fit for the Popup Control

**Comment by sarthak1995-26** [comment] 2020-12-13 15:42
Yes dismissal of popup on click outside might be a problem. I was thinking of a control that could allow us to achieve something like a below gif without going on a native stuff.Since developer might want customise ListView template or show completely different content(like showing some tooltip info contentview) which might be a time taking process if it comes to customise spinner and other native way to achieve something like this.

https://raw.githubusercontent.com/XamFormsExtended/Xfx.Controls/master/resources/xfx.controls.ios.gif

**Comment by sarthak1995-26** [comment] 2020-12-13 15:48
Entry would be present on a content page while we are showing and hiding overlay control on some specific x,y position without making entry to be unfocused while writing which would happen if we use Rg.Plugin.Popup for this.

**Comment by AndreiMisiukevich** [comment] 2020-12-13 19:07
@sarthak1995-26 duplicate of https://github.com/xamarin/XamarinCommunityToolkit/issues/294

**Closed** 2020-12-13 19:08 UTC
Labels: duplicate

**Comment by SarthakGz** [comment] 2022-03-24 07:26
This is what actually I was asking for https://github.com/jsuarezruiz/netmaui-overlay-playground actually
still I am not sure how can I add MAUI controls to overlay view yet but its a start :)
