### ISSUE TITLE
[Bug][TouchEffect] Resetting Application.MainPage leads to ArgumentNullException

### ISSUE THREAD

**Issue by Huaba93** [xamarin/XamarinCommunityToolkit#1066] opened 2021-03-12 12:36 UTC
### Description
Resetting Application.MainPage leads to ArgumentNullException. I have also seen this with back navigation, but cannot reproduce it there on a regular basis.

Setting a new MainPage occurs frequently when using Prism. Absolute navigation sets a new MainPage.
For more infos about relative/absolute navigation see [Prisms documentation.](https://prismlibrary.com/docs/xamarin-forms/navigation/navigation-basics.html#navigating)

```
System.ArgumentNullException: Value cannot be null.
Parameter name: bindable
  at Xamarin.CommunityToolkit.Effects.TouchEffect.GetCommandParameter (Xamarin.Forms.BindableObject bindable) [0x00003] in <809c99546a8b4714a1709bd678b27282>:0 
  at Xamarin.CommunityToolkit.Effects.TouchEffect.get_CommandParameter () [0x00006] in <809c99546a8b4714a1709bd678b27282>:0 
  at Xamarin.CommunityToolkit.Effects.TouchEffect.RaiseCompleted () [0x0000c] in <809c99546a8b4714a1709bd678b27282>:0 
  at Xamarin.CommunityToolkit.Effects.GestureManager.OnTapped (Xamarin.CommunityToolkit.Effects.TouchEffect sender) [0x0005e] in <809c99546a8b4714a1709bd678b27282>:0 
  at Xamarin.CommunityToolkit.Effects.GestureManager.HandleTouch (Xamarin.CommunityToolkit.Effects.TouchEffect sender, Xamarin.CommunityToolkit.Effects.TouchStatus status) [0x00105] in <809c99546a8b4714a1709bd678b27282>:0 
  at Xamarin.CommunityToolkit.Effects.TouchEffect.HandleTouch (Xamarin.CommunityToolkit.Effects.TouchStatus status) [0x00000] in <809c99546a8b4714a1709bd678b27282>:0 
  at Xamarin.CommunityToolkit.iOS.Effects.TouchUITapGestureRecognizer.HandleTouch (Xamarin.CommunityToolkit.Effects.TouchStatus status, System.Nullable`1[T] interactionStatus) [0x0009b] in <809c99546a8b4714a1709bd678b27282>:0 
  at Xamarin.CommunityToolkit.Helpers.SafeFireAndForgetExtensions.HandleSafeFireAndForget[TException] (System.Threading.Tasks.Task task, System.Boolean continueOnCapturedContext, System.Action`1[T] onException) [0x0006f] in <809c99546a8b4714a1709bd678b27282>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 
  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAction.cs:178 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:65 
  at TouchEffectNullReference.iOS.Application.Main (System.String[] args) [0x00001] in /Users/christophhuber/git/XamarinIssues/TouchEffectNullReference/TouchEffectNullReference/TouchEffectNullReference.iOS/Main.cs:16 
```

### Steps to Reproduce
Set a new Application.MainPage on a Button tap (or press on "Absolute Navigation" in the attached sample)

### Expected Behavior
TouchEffect should work regardless of what type of navigation is used. 

### Actual Behavior
App crashes on absolute navigation.

### Basic Information

- Version with issue: Tested all available versions (even prereleases)
- Last known good version: -
- Platform Target Frameworks: 
  - iOS:  14
  - Android: 10
- Affected Devices: Tested on some simulators, iPhone 12 iOS 14 and samsung galaxy 10 android 10

### Reproduction Link

https://github.com/Huaba93/XamarinIssues/tree/master/TouchEffectNullReference

**Comment by AndreiMisiukevich** [comment] 2021-03-13 17:09
Hello @Huaba93 and thanks for the report :) I will take a look

**Comment by AndreiMisiukevich** [comment] 2021-03-16 00:41
Closed in #1078

**Closed by AndreiMisiukevich** 2021-03-16 00:41 UTC
Labels: a/TouchEffect, bug, p/android, p/iOS

**Comment by nor0x** [comment] 2021-03-16 06:42
i have tried the NuGets from #1078 but i'm still having this issue - on UWP however where it leads to the following exception

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xamarin.CommunityToolkit.UWP.Effects.PlatformTouchEffect.OnPointerReleased(Object sender, PointerRoutedEventArgs e)
```

**Comment by AndreiMisiukevich** [comment] 2021-03-16 21:26
Hey @nor0x, it seems it's a different issue (at least because I applied fixes to shared logic).
Could you please share more info about reproducing this crash. What was the scenario? (changing Application.MainPage or something else?)

Thanks

**Comment by nor0x** [comment] 2021-03-17 11:12
Hi @AndreiMisiukevich i have replied directly in the PR - in my case i'm also replacing the MainPage at some point of the application lifecycle

**Comment by Huaba93** [comment] 2021-04-20 13:26
Works now. Thank you!
