### ISSUE TITLE
[Bug] DisplaySnackBarAsync does not wait for action task

### ISSUE THREAD

**Issue by Dreamescaper** [xamarin/XamarinCommunityToolkit#1340] opened 2021-05-27 21:52 UTC
### Steps to Reproduce

Debug the following code, and tap on "Retry" button.
```csharp
            bool invoked = false;
            var result = await page.DisplaySnackBarAsync("test", "Retry", async () =>
             {
                 await Task.Delay(3000);
                 invoked = true;
                 // Breakpoint1
             });

            // Breakpoint2
```

### Expected Behavior
Retry action is awaited, Breakpoint2 is hit after Breakpoint1.

### Actual Behavior
Retry action is not awaited, Breakpoint1 is hit after Breakpoint2.

### Basic Information

- Version with issue: 1.1.0
- Platform Target Frameworks:
  - Android

### Workaround
I did something like that:
```csharp
            bool invoked = false;
            Task retryTask = null;
            var snackbarResult = await page.DisplaySnackBarAsync(text, "Retry", async () =>
            {
                async Task RetryAction()
                {
                    await Task.Delay(3000);
                    invoked = true;
                }
                retryTask = RetryAction();
                await retryTask;
            });

            if (snackbarResult)
            {
                await retryTask;
            }
```

**Comment by pictos** [comment] 2021-05-30 00:50
@Dreamescaper 
Could you attach a small repro?

**Comment by Dreamescaper** [comment] 2021-05-30 13:15
Sure!
I've attached sample project. Start the project, click on "Show SnackBar" button, then click on "Action" button on snackbar.

Expected: 
actionTask.Status should be `RanToCompletion` when execution continues after `await this.DisplaySnackBarAsync`.

Actual:
actionTask.Status is `WaitingForActivation` when execution continues after `await this.DisplaySnackBarAsync`.

[Repro.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/6566251/Repro.zip)

**Comment by maxkoshevoi** [comment] 2021-06-02 19:32
I think this is by design. 
`await this.DisplaySnackBarAsync` completes when SnackBar is no longer displayed (regardless whether SnackBar action is being executed or now), and clicking on `Action` - hides the SnackBar. 

If you want to wait until cation completes, you'll need to write some custom code.

**Comment by Dreamescaper** [comment] 2021-06-02 19:51
@maxkoshevoi 
But what's the point of having `action` as `Func<Task>` instead of simple `Action`? If it's never awaited?

**Comment by maxkoshevoi** [comment] 2021-06-02 20:07
@Dreamescaper I guess there's no point. 

At the end it's just passed as an action argument:
https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/SnackBar.android.cs#L67

**Comment by Dreamescaper** [comment] 2021-06-02 20:14
@maxkoshevoi 
https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/SnackBar.ios.macos.cs#L119 

I don't have an iOS device to check, but as far as I can see based on code, ios implementation _does_ await an action _before_ completion.

**Comment by maxkoshevoi** [comment] 2021-06-02 21:19
Good point. Updated #1357 to include fix for this. Also passed exceptions from SnackBar action into resulting task, so you can catch them in your code.

**Closed** 2021-11-25 12:52 UTC
Labels: bug, s/unverified, a/Snackbar
