### ISSUE TITLE
[Bug] XCT doesn't build "Release | iPhone" builds for iOS - AOT fails

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/XamarinCommunityToolkit#368] opened 2020-10-04 14:49 UTC
### Description

Xamarin.Forms 5-pre1 is announcing XCT as an upgrade path for certain features that were present in Xamarin.Forms 4. Unfortunately the following error happens when building "Release | iPhone" for iOS:

`/Users/myname/Projects/MyProject/MyApp.iOS/MTOUCH: Error MT3001: Could not AOT the assembly '/Users/myname/Projects/MyProject/MyApp.iOS/obj/iPhone/Development/mtouch-cache/3-Build/Xamarin.CommunityToolkit.dll' (MT3001) (MyApp.iOS)`

Full build step error:

```
Target _CompileToNative:
    /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/myname/Projects/MyProject/MyApp.iOS/obj/iPhone/Development/response-file.rsp 
    Xamarin.iOS 14.0.0.0 (xcode12): 7ec3751a1 using framework: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.0.sdk
    AOT Compilation exited with code 1, command:
    MONO_PATH=/Users/myname/Projects/MyProject/MyApp.iOS/obj/iPhone/Development/mtouch-cache/3-Build /Library/Frameworks/Xamarin.iOS.framework/Versions/14.0.0.0/bin/arm64-darwin-mono-sgen --debug --llvm -O=gsharedvt -O=float32 --aot=mtriple=arm64-ios,data-outfile=/Users/myname/Projects/MyProject/MyApp.iOS/obj/iPhone/Development/mtouch-cache/arm64/Xamarin.CommunityToolkit.aotdata.arm64,static,asmonly,direct-icalls,full,nodebug,dwarfdebug,msym-dir=/Users/myname/Projects/MyProject/MyApp.iOS/obj/iPhone/Development/mtouch-cache/3-Build/Msym,llvm-path=/Library/Frameworks/Xamarin.iOS.framework/Versions/14.0.0.0/LLVM/bin/,outfile=/Users/myname/Projects/MyProject/MyApp.iOS/obj/iPhone/Development/mtouch-cache/arm64/Xamarin.CommunityToolkit.dll.s,llvm-outfile=/Users/myname/Projects/MyProject/MyApp.iOS/obj/iPhone/Development/mtouch-cache/arm64/Xamarin.CommunityToolkit.dll-llvm.o /Users/myname/Projects/MyProject/MyApp.iOS/obj/iPhone/Development/mtouch-cache/3-Build/Xamarin.CommunityToolkit.dll
    Mono Ahead of Time compiler - compiling assembly /Users/myname/Projects/MyProject/MyApp.iOS/obj/iPhone/Development/mtouch-cache/3-Build/Xamarin.CommunityToolkit.dll
    AOTID F66F0FEA-256C-772B-6626-54B80610969B
    Failed to load method 0x60001c9 from '/Users/myname/Projects/MyProject/MyApp.iOS/obj/iPhone/Development/mtouch-cache/3-Build/Xamarin.CommunityToolkit.dll' due to Could not resolve type with token 0100004a from typeref (expected class 'Xamarin.Forms.MediaSource' in assembly 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null type:Xamarin.Forms.MediaSource member:(null).
    Run with MONO_LOG_LEVEL=debug for more information.
    AOT of image /Users/myname/Projects/MyProject/MyApp.iOS/obj/iPhone/Development/mtouch-cache/3-Build/Xamarin.CommunityToolkit.dll failed.
    MTOUCH : error MT3001: Could not AOT the assembly '/Users/myname/Projects/MyProject/MyApp.iOS/obj/iPhone/Development/mtouch-cache/3-Build/Xamarin.CommunityToolkit.dll'
```

Considering that it mentions 'Xamarin.Forms.MediaSource' it leads me to believe this is related to the linker issue with XCT's MediaSource/MediaCapturedEventArgs reported here: https://github.com/xamarin/XamarinCommunityToolkit/issues/367.

As this blocks testing on and distributing to actual devices I'd urge to ship a fixed package soon, as it also prevents proper testing of Xamarin.Forms 5 preview releases.

(Personally I am not using media source at all.)

Thanks.

### Steps to Reproduce

1. Add the latest XCT NuGet to a Xamarin.Forms 5 project.
2. Due to https://github.com/xamarin/XamarinCommunityToolkit/issues/367, you have to set 'Linker behaviour' to 'Don't link', to work around that issue.
3. Build for iOS with target set to "Release | iPhone" (don't use "Release | iPhoneSimulator" as that builds fine). "Debug | iPhone" may also give the same error but I didn't test it.
4. The above build error prevents the build from succeeding.

### Expected Behavior

iOS "Release | iPhone" and "Debug | iPhone" builds should finish successfully.

### Actual Behavior

iOS "| iPhone" builds fail with the above error.

### Basic Information

- Version with issue: 1.0.0-pre3
- IDE: VS For Mac 8.7.8 build 4F
- Nuget Packages: Xamarin.Forms 5-pre1

### Workaround

None.

**Comment by pictos** [comment] 2020-10-05 00:28
@Tommigun1980 if you run your project using XF 4.8 + XCT packages, does this error occurs?

**Comment by Tommigun1980** [comment] 2020-10-05 15:34
> @Tommigun1980 if you run your project using XF 4.8 + XCT packages, does this error occurs?

Hi @pictos. I just tested and the error does not happen with XF 4.8. However, XF 5.0's release notes say that XCT is the upgrade path so I think it's paramount to have compatibility with it as well.

Thanks.

**Comment by pictos** [comment] 2020-10-05 15:35
@Tommigun1980, yeah you are right! I asked just to make sure that isn't a linker issue. Thanks for your feedback❣

**Comment by Tommigun1980** [comment] 2020-10-05 15:36
> @Tommigun1980, yeah you are right! I asked just to make sure that isn't a linker issue. Thanks for your feedback❣

For sure, I was just stating the obvious. Thanks for looking into this!

**Comment by Tommigun1980** [comment] 2020-10-08 20:37
Hi guys. Any idea when https://github.com/xamarin/XamarinCommunityToolkit/issues/367 and https://github.com/xamarin/XamarinCommunityToolkit/issues/368 will be in a release so that XCT is Xamarin.Forms 5 compatible? Considering that XCT is *the* upgrade path for Xamarin.Forms 5 I think this is something that should make its way into a release ASAP. Thanks.

**Comment by AndreiMisiukevich** [comment] 2020-10-11 15:38
@pictos Did your PR fix this issue? What do you think? (I mean bringing media source to XCT) Thx

**Comment by pictos** [comment] 2020-10-11 18:07
@AndreiMisiukevich that PR fixes #367 for sure (I hope). This one can be related to a more general issue with the linker process. I'll find a time to investigate it. I'll try to reproduce here and try to fix, but @Tommigun1980 if you can attach a sample repo would be awesome! 
As you described looks pretty simple to reproduce, but I'm afraid to miss some step that you do.

**Comment by jfversluis** [comment] 2020-10-14 07:08
Seems this might be fixed already with the afore mentioned PR. But let's check this on a physical device in release configuration anyway just to be sure.

**Comment by Tommigun1980** [comment] 2020-10-14 10:05
Hi. I tested XCT's latest bleeding edge version and I can confirm that this issue is fixed! Thanks a lot.

**Comment by pictos** [comment] 2020-10-17 04:33
@Tommigun1980, just to confirm. Can we close this issue?

**Comment by pictos** [comment] 2020-10-17 04:34
Since @Tommigun1980 confirms that is fixed, I'll close this issue.

@Tommigun1980 thank you so much for trying our releases builds <3

**Closed by pictos** 2020-10-17 04:34 UTC
Labels: bug, p/iOS, s/unverified
