### ISSUE TITLE
Image rotation

### ISSUE THREAD

**Issue by Zubairhanif06** [xamarin/XamarinCommunityToolkit#779] opened 2021-01-19 12:14 UTC
i'm using camera view in my page. after capturing image it rotes the image in android .
i'm testing this on real device . Samsung SM J400F (Android 10.0 API 29)

![processed](https://user-images.githubusercontent.com/61466735/105032187-49765800-5a78-11eb-8a6e-ecd54380c23e.jpeg)
![c1](https://user-images.githubusercontent.com/61466735/105032386-85a9b880-5a78-11eb-9256-aa9bd82ae9ae.jpeg)

here is my xml code 
<StackLayout>
        <xct:CameraView x:Name="camera" CaptureMode="Photo"
                FlashMode="Off" 
                         Zoom="0" 
                        IsAvailable="True"
                         CameraOptions="Back"
                        MediaCaptured="CameraView_MediaCaptured"
                HorizontalOptions="FillAndExpand"
                VerticalOptions="FillAndExpand">

        </xct:CameraView>
        <Button
            x:Name="doCameraThings"
                    Command="{Binding ShutterCommand, Source={x:Reference camera}}"
                    IsEnabled="True"
                    Text="Start Recording" />
        <Image
                    x:Name="previewPicture"
                    Aspect="AspectFit"
                    BackgroundColor="LightGray"
                    HeightRequest="250"
                    IsVisible="False" />
    </StackLayout>

**Comment by Cfun1** [comment] 2021-01-19 12:29
@pictos, @AndreiMisiukevich  or @jfversluis  is it normal that this issue has no default labels attached to it ?

**Comment by jfversluis** [comment] 2021-01-19 12:34
Looks like the template wasn't used :)

Thanks for the report @Zubairhanif06 this seems like a duplicate of #751 please add further details there, and for a next issue please use the appropriate template. Thank you!

**Comment by jfversluis** [comment] 2021-01-19 12:34
Duplicate of #751

**Closed by jfversluis** 2021-01-19 12:34 UTC

**Comment by Zubairhanif06** [comment] 2021-01-19 12:36
thanks , i will let you know .
