### ISSUE TITLE
MediaElement [Bug] On Windows 11 OnMediaEnded the line "video.Source = path" throw WRONG THREAD

### ISSUE THREAD

**Issue by behemothe** [xamarin/XamarinCommunityToolkit#1985] opened 2023-09-18 12:37 UTC

**Comment by behemothe** [comment] 2023-09-18 13:15
I don't saw this issue so I do again

**Comment by bijington** [comment] 2023-09-18 14:47
Duplicate of #1986

**Closed** 2023-09-18 14:47 UTC
Labels: bug, maui-compat
