### ISSUE TITLE
[Bug] TouchEffect.NativeAnimation fires twice on Android

### ISSUE THREAD

**Issue by Symxn** [xamarin/XamarinCommunityToolkit#879] opened 2021-02-10 12:54 UTC
### Description

On Android, the ripple effect is carried out twice in a row when you briefly tap an element.
I cannot currently check whether the problem also exists with iOS.

### Steps to Reproduce

1. Add a grid to your page
2. Set on the grid TouchEffect.NativeAnimation="True"
3. Run the app and briefly tap the grid

### Expected Behavior

The ripple effect is displayed once.

### Actual Behavior

The ripple effect is displayed twice.

### Basic Information

- Version with issue: 1.0.2
- Last known good version: -
- IDE: Visual Studio 2019 Community
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by Cfun1** [comment] 2021-02-10 13:01
Duplicate of already fixed https://github.com/xamarin/XamarinCommunityToolkit/issues/804
@Symxn please check https://github.com/xamarin/XamarinCommunityToolkit/pull/817 it will be fixed in the next release
cc @AndreiMisiukevich

**Comment by jfversluis** [comment] 2021-02-10 14:01
Duplicate of #804

**Closed by jfversluis** 2021-02-10 14:01 UTC
Labels: bug, s/unverified
