### ISSUE TITLE
[Bug]  EventToCommandBehavior - When a converter returns null the command is called with original EventArgs instead of null

### ISSUE THREAD

**Issue by WilliamV-Info** [xamarin/XamarinCommunityToolkit#962] opened 2021-02-22 16:32 UTC
### Description
When a converter returns null the command is called with original EventArgs instead of null.
Say you have a converter for a model and a command that expects that model.
If the converter results in null the command is not called with null.

I believe the null check [here](https://github.com/xamarin/XamarinCommunityToolkit/blob/8e1e29744776e2c3675282f832a9eb25a5bd01f8/src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/EventToCommandBehavior.shared.cs#L129) at 129 is the culprit.
The [Microsoft sample code for EventToCommandBehavior](https://github.com/xamarin/xamarin-forms-samples/blob/master/Behaviors/EventToCommandBehavior/EventToCommandBehavior/Behaviors/EventToCommandBehavior.cs#L102) also works differently.

### Steps to Reproduce

1.  Create an EventToCommandBehavior
2.  Add a converter
3.  Make sure the converter returns null
4.  Have a command expect a certain type like string
5.  Notice how that command is not called when the converter returns null

### Expected Behavior

Command to be called with null.
Like in [this](https://github.com/xamarin/xamarin-forms-samples/blob/master/Behaviors/EventToCommandBehavior/EventToCommandBehavior/Behaviors/EventToCommandBehavior.cs#L102) Microsoft sample code.

### Actual Behavior

Command is not called with null, its called with EventArgs which doesn't work

### Basic Information

- Version with issue: v1.0.3
- Last known good version: -
- IDE: VS2019
- Platform Target Frameworks:
  - Android: 10
- Nuget Packages:
- Affected Devices:

### Workaround
Always return an object, if necessary a wrapper of sorts

### Fix
[EventToCommandBehavior](https://github.com/xamarin/XamarinCommunityToolkit/blob/8e1e29744776e2c3675282f832a9eb25a5bd01f8/src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/EventToCommandBehavior.shared.cs#L127)
I'm willing to create a PR which would probably look something like this:
`
var parameter = CommandParameter
    ?? (EventArgsConverter != null ? EventArgsConverter.Convert(eventArgs, typeof(object), null, null) :
    eventArgs);
`
instead of the current :
`
var parameter = CommandParameter
    ?? EventArgsConverter?.Convert(eventArgs, typeof(object), null, null)
    ?? eventArgs;
`

**Comment by pictos** [comment] 2021-03-16 23:26
Duplicate of #953

**Closed by pictos** 2021-03-16 23:26 UTC
Labels: bug, s/unverified
