### ISSUE TITLE
[Enhancement] Round corner converter

### ISSUE THREAD

**Issue by IeuanWalker** [xamarin/XamarinCommunityToolkit#602] opened 2020-11-21 19:00 UTC
## Summary

A converter to set the corner radius of a control based on its height to make it rounded.

## API Changes

New converter -
```csharp
public class RoundCornerRadiusConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
        return !(value is double doubleValue) ? 0 : (object)(int) (doubleValue / 2);
    }

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
    {
        throw new NotImplementedException();
    }
}
```

Usage -
```xaml
CornerRadius="{Binding Source={RelativeSource Self}, Path=Height, Converter={StaticResource RoundCornerRadiusConverter}}"
```
## Intended Use Case
An example used in one of my app - 
![image](https://user-images.githubusercontent.com/6544051/99885311-ced1bd80-2c2b-11eb-8e0e-efe828c6a148.png)

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

**Comment by jBijsterboschNL** [comment] 2020-11-21 20:48
I like your idea and could use this for several use cases in my own projects. But wouldn't a Behavior be a better fit for this?
You could create a Behavior that works for all views that have a CornerRadius property and when the Height property of that control has changed, you could update the CornerRadius as well.
The usage would be much easier also.
And perhaps you could make it a bit more generic to add an option as well to determine the CornerRadius depending on the view's Height as well as for the view's Width? If you are using a more vertical oriented view instead of a horizontal view as you've mentioned in your example?!
Let me know what you think of my suggestions and if you need any help with this :) thank you for creating this issue!

**Comment by IeuanWalker** [comment] 2020-11-21 21:15
@jBijsterboschNL sounds good.

Havnt created many behaviours so be interesting how id do that.

In my project I'm using pancake view, would a behaviour able able to be generic enough to work for custom control like that or would it be limited to XF controls ?

**Comment by jBijsterboschNL** [comment] 2020-11-21 21:23
> In my project I'm using pancake view, would a behaviour able able to be generic enough to work for custom control like that or would it be limited to XF controls ? 

I was already afraid you would say you where using the PancakeView, or any non default Xamarin.Forms view 🙈 then you would need to use reflection in the Behavior to check if the View has a property named CornerRadius, but don't think that's such a good idea...

If you would go for a Converter, you could as well make it a bit more generic to create a MathConverter perhaps? With 2 proporties, Operator and OperatorValue. Where you could set Divide as the Operator (which is a custom enum type) and 2 as the OperatorValue. To make your xaml still easy readable you could create this in your Xaml:

`<xct:MathConverter x:Key="RoundedCornersConverter" Operator="Divide" OperatorValue=2 />

CornerRadius="{Binding ..., Converter='{StaticResource RoundedCornersConverter}'"`

**Comment by jBijsterboschNL** [comment] 2020-11-22 06:38
Or if you still want to go with the Behavior, you could make the method that sets the CornerRadius virtual and in your own project you can create a PancakeViewRoundedCornersBehavior and override that method to properly set the CornerRadius on the PancakeView.

**Comment by IeuanWalker** [comment] 2020-11-22 15:36
@jBijsterboschNL Probably best to stick with a converter for now.

Just need the go-ahead before I implement this.

**Comment by AndreiMisiukevich** [comment] 2020-11-23 08:44
Hi) Behavior is more suitable here, I think

**Comment by roubachof** [comment] 2020-11-23 09:46
I'm afraid `RoundCornerRadiusConverter` is not really suitable as a name since it just basically divides by 2 the argument.
Also a Behavior seems a bit at the same time too powerful for the wanted operation and at the same time incomplete:

It would only work for Frame and need to extend it to support thrid party libs like pancake.

So I guess a `MathOperationValueConverter` would have more sense as described by @jBijsterboschNL.
It makes me think that we could have a "tips and tricks" section in the wiki to describe all the things that can be implemented easily in XF based on the experience of the users.

The auto round view trick, should be then part of this section:

```xml
<Style x:Key="RoundedFrame"
           ApplyToDerivedTypes="True"
           TargetType="Frame">
        <Setter Property="CornerRadius" 
                     Value="{Binding Source={RelativeSource Self}, Path=Height, Converter={converters:MathOperationValueConverter  Operator="Divide" Operand=2}}" />

```

**Comment by IeuanWalker** [comment] 2020-11-24 20:11
@roubachof cool no prob, I'll look at implementing this, this week or on the weekend :)

**Comment by pictos** [comment] 2020-11-26 23:14
I'm wondering if we really need this feature. I can't remember to need something like this in any real app, even to calculate the Radius. Also, a converter is very bad for this, because we box and unbox values and for math operations, we just use values type. Said that we'll box every time that we need to perform a calculation.

**Comment by IeuanWalker** [comment] 2020-11-26 23:35
> I'm wondering if we really need this feature. I can't remember to need something like this in any real app, even to calculate the Radius. Also, a converter is very bad for this, because we box and unbox values and for math operations, we just use values type. Said that we'll box every time that we need to perform a calculation.

Ye i dont mind.

I needed this for my app to calculate the CornerRadius dynamically as the height of the frame could vary based on the device width or the content of the update, so the CornerRadius couldn't be set as a constant.

**Comment by pictos** [comment] 2020-11-26 23:42
> @pictos Ye i dont mind.
> 
> I needed this for my app to calculate the CornerRadius dynamically as the height of the frame could vary based on the device width or the content of the update, so the CornerRadius couldn't be set as a constant.

@IeuanWalker first of all, thanks for the propuse. 

And don't get me wrong here. By your answer, if it's just you, I think that you can implement it just on your app. The concept of XCT isn't to add features that **your** app needs and feature that will e useful for various apps. And the feature also needs to make sense.

**Comment by AndreiMisiukevich** [comment] 2020-11-26 23:47
@pictos @IeuanWalker 

I assumed something similar but more powerful

https://github.com/xamarin/XamarinCommunityToolkit/issues/237

Maybe sometimes it can be useful (multiply to some value)

e.g. If I need set an element's width equal to 30% of the parent's width (And I don't want to sue Absolute or Relative layout and want to use Stack)

Or when Opacity must depend on TranslationX etc.

**Comment by pictos** [comment] 2020-11-26 23:58
@AndreiMisiukevich I got your point and took a look at two references in #237. That makes much more sense to add because is more powerful. But why not use the code-behind for stuff like that?

**Comment by AndreiMisiukevich** [comment] 2020-11-27 00:33
> @AndreiMisiukevich I got your point and took a look at two references in #237. That makes much more sense to add because is more powerful. But why not use the code-behind for stuff like that?

Well, I am a C# for UI fan :) So this is a very interesting topic. But as I know other devs are keen to reduce C# percentage as much as possible :)

**Comment by pictos** [comment] 2020-11-27 00:39
So I think that is reasonable to mark this as duplicated or related to #237 and close this one.

**Closed** 2020-11-27 00:40 UTC
Labels: feature-request, needs-approval, needs-more-discussion

**Comment by pictos** [comment] 2020-11-27 00:42
@IeuanWalker thanks again for your proposal, lets continue this discussion on #237 issue. I'll mark your PR with the `not-on-roadmap` label since that's not the implementation that we want. We'll be very happy if you want to move forward with th #2367 but please wait that the issue is marked with `ready-to-implement` label.
