### ISSUE TITLE
[Bug] In UWP, Tab results are missing

### ISSUE THREAD

**Issue by WillAutioItrax** [xamarin/XamarinCommunityToolkit#872] opened 2021-02-09 17:34 UTC
### Description
When I run the samples on UWP, the Tabs appear but when I tap/click on them the resulting page has nothing (except for C# markup).

### Steps to Reproduce

1. Download current code from github.
2. Run the Samples in Android
3. Run the Samples in UWP
4. Compare the two

### Expected Behavior
Both would look fairly similar.
### Actual Behavior
1) In Android, when a tab is tapped, several additional samples appear on the next page.
2) in UWP, when a tab is tapped, only the C# Markup tab opens a new page with additional stuff. All the other tabs open a new page with no further samples.
### Basic Information

- Version with issue: current as of Feb 9, 2021
- Last known good version: first one that I have tried.
- IDE: VS 2019 16.8.4
- Platform Target Frameworks: 
  - iOS:   did not try
  - Android:  10.0 
  - UWP:   18362
- Android Support Library Version: 
- Nuget Packages: Default ones that come with the download
- Affected Devices: PC

**Comment by jfversluis** [comment] 2021-02-09 19:40
Hey @WillAutioItrax thanks for the report! Yeah, we're aware, sorry about that :( It's actually #606
Good news, for now, is that you can work around it by resizing the window to make it show up so you can still try it

**Comment by jfversluis** [comment] 2021-02-09 19:40
Duplicate of #606

**Closed by jfversluis** 2021-02-09 19:40 UTC
Labels: bug, s/unverified
