### ISSUE TITLE
[Bug] Cannot Build Solution On Visual Studio For Mac 2019 After 1.3.1

### ISSUE THREAD

**Issue by Axemasta** [xamarin/XamarinCommunityToolkit#1805] opened 2022-02-01 19:08 UTC
### Description

This isn't really a bug but it has affected me all the same so I thought it would be best to ask here.

Since version 1.3.1 of the library I cannot build the project locally using visual studio for mac. I have confirmed by running the 1.3.1 commit (35d7d5f7620110a55de9ec8a1afd0397e64b4d10) without issue:
![1.3.1 working locally](https://user-images.githubusercontent.com/33064621/152033068-d7971055-9f8e-4ffc-9cfd-968403de1757.png)

When i go to 1.3.2 or higher, i get the following error:
![Issue using 2.0.0](https://user-images.githubusercontent.com/33064621/152033442-ef2610fe-110f-43ff-a108-40a9054db593.png)

```
Error: .NET Core 1.0 SDK is required to build this application, and is not installed. 
Install the latest update to the .NET Core 1.0 SDK by visiting https://aka.ms/vs/mac/install-netcore1 (Xamarin.CommunityToolkit)
```
```
Error: .NET Core 2.0 SDK is required to build this application, and is not installed. 
Install the latest update to the .NET Core 2.0 SDK by visiting https://aka.ms/vs/mac/install-netcore2 (Xamarin.CommunityToolkit.Markup)
```
I followed the urls & downloaded the .NET 2.0 SDK as instructed, installed & get the same error. Interestingly the link for .NET Core 1.0 sdk doesn't take you anywhere, I got redirected to bing.... [https://aka.ms/vs/mac/install-netcore1](https://aka.ms/vs/mac/install-netcore1)

I can build this code & run it from windows, its just mac that is affected. I daily drive mac for development, so I would like to get this issue resolved. Could this be an issue with workloads & maui? I do have visual studio 2022 preview installed on the mac aswell. I know some of you in the team do use macs & maybe this is something youve come across?

### Basic Information

- Version with issue: 1.3.2 & above
- Last known good version: 1.3.1
- IDE: Visual Studio For Mac 2019

### IDE Details

<details>
<summary>expand to see ide details</summary>

```
=== Visual Studio Professional 2019 for Mac ===

Version 8.10.17 (build 2)
Installation UUID: 65f9ab1b-a127-4a98-ac20-f9fb7510f8b9
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000162

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.162 (2020-02/2ca650f1f62) (64-bit)
	Package version: 612000162

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/sdk/6.0.101/Sdks
SDK Versions:
	6.0.101
	6.0.100
	5.0.404
	5.0.403
	5.0.402
	5.0.401
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.416
	3.1.415
	3.1.414
	3.1.413
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.300
	3.1.201
	2.1.202
	2.0.0
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.1
	6.0.0
	5.0.13
	5.0.12
	5.0.11
	5.0.10
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.22
	3.1.21
	3.1.20
	3.1.19
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.4
	3.1.3
	2.1.23
	2.0.9
	2.0.0

=== .NET Core 3.1 SDK ===

SDK: 3.1.416

=== .NET 5.0 SDK ===

SDK: 5.0.404

=== Xamarin.Profiler ===

Version: 1.7.0.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 13.2.1 (19586)
Build 13C100

=== Xamarin.Mac ===

Version: 8.4.0.0 (Visual Studio Professional)
Hash: 8fc41ae82
Branch: xcode13.2
Build date: 2021-12-09 01:07:56-0500

=== Xamarin.iOS ===

Version: 15.4.0.0 (Visual Studio Professional)
Hash: 8fc41ae82
Branch: xcode13.2
Build date: 2021-12-09 01:07:56-0500

=== Xamarin Designer ===

Version: 16.11.0.60
Hash: 56f9b80b0
Branch: remotes/origin/d16-11
Build date: 2021-12-15 02:44:16 UTC

=== Xamarin.Android ===

Version: 12.0.0.3 (Visual Studio Professional)
Commit: xamarin-android/d16-11/f0e3c2d
Android SDK: /Users/alex.duffell/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 30.0.3

Build Information: 
Mono: c633fe9
Java.Interop: xamarin/java.interop/d16-11@476bb5b
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

=== Eclipse Temurin JDK ===

Java SDK: Not Found

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:52 UTC

=== Build Information ===

Release ID: 810170002
Git revision: 58f7763d4d64fcf005a474d25a5d9fd5ce46d7f5
Build date: 2022-01-05 12:51:28-05
Build branch: release-8.10

=== Operating System ===

Mac OS X 11.4.0
Darwin 20.5.0 Darwin Kernel Version 20.5.0
    Sat May  8 05:10:33 PDT 2021
    root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

DeepClean 1.2.5
Code Distribution Extension 1.1
LightSwitch 💡 1.0
Code Coverage 2.0.1
```

</details>

**Comment by Axemasta** [comment] 2022-02-01 21:59
Deleting `global.json` seemed to fix the issue, what can we do to make this backwards compatible? I have VS2022 installed on this machine but not all of the Maui workloads so I can't confirm if they are mandatory.

**Comment by cris-m** [comment] 2022-02-02 13:52
> Deleting `global.json` seemed to fix the issue, what can we do to make this backwards compatible? I have VS2022 installed on this machine but not all of the Maui workloads so I can't confirm if they are mandatory.

I am still getting the issue after deleting the ``global.json`` file.
<img width="1792" alt="Screen Shot 2022-02-02 at 22 51 17" src="https://user-images.githubusercontent.com/29815096/152166704-dbc15d90-5bd2-4715-a9bc-ea586ff65069.png">

**Comment by bijington** [comment] 2022-02-03 08:52
@Axemasta interestingly I don't even have .NET Core 2.0 installed on my Mac.

```txt
=== Visual Studio Community 2019 for Mac ===

Version 8.10.17 (build 2)
Installation UUID: 90063c96-7a7b-40b6-8287-01330f9f04fc
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000162

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/x64/sdk/6.0.101/Sdks
SDK Versions:
	6.0.101
	5.0.404
	3.1.416
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	6.0.1
	5.0.13
	3.1.22

=== .NET Core 3.1 SDK ===

SDK: 3.1.416

=== .NET 5.0 SDK ===

SDK: 5.0.404
```

It may well be that 2022 and 2019 are not playing nicely as I don't have 2022 installed and I can compile fine.

I know recently I had issues when installing a version of .NET 6.0 preview, it broke many things like PowerShell core and other things. Sadly the fix there was to completely remove all versions of .NET Core Runtime and SDK and then install these above. Wiping all may have been overkill but it seemed to make sense to get back to a level of cleanliness before building back up again.

**Comment by Axemasta** [comment] 2022-02-03 10:03
@bijington I will have a go at uninstalling all of the different versions on my mac and see if that makes a difference. If this does help might I suggest we create a development guide, akin to the ones seen in [forms](https://github.com/xamarin/Xamarin.Forms#getting-started) & [maui](https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md)?

**Comment by bijington** [comment] 2022-02-03 10:37
> @bijington I will have a go at uninstalling all of the different versions on my mac and see if that makes a difference. If this does help might I suggest we create a development guide, akin to the ones seen in [forms](https://github.com/xamarin/Xamarin.Forms#getting-started) & [maui](https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md)?

I am all for any documentation to aid the development process :) good idea!

**Comment by VladislavAntonyuk** [comment] 2022-02-22 07:29
@Axemasta could you please pull the latest changes? I removed netcoreapp2.0 dependency

**Comment by VladislavAntonyuk** [comment] 2022-03-21 12:42
@Axemasta we did get feedback from you. I am closing the issue for now. If the issue is still reproduced, please reopen it again.

**Closed by VladislavAntonyuk** 2022-03-21 12:43 UTC
Labels: bug
