### ISSUE TITLE
[Bug] NullReferenceException when displaying Toast or SnackBar

### ISSUE THREAD

**Issue by maxkoshevoi** [xamarin/XamarinCommunityToolkit#959] opened 2021-02-22 15:06 UTC
### Description

It's a bit tricky to reproduce, but I think it happens when you display toast and change page at the same time.

Here's how ViewModel displays the toast:
```cs
await Shell.Current?.CurrentPage?.DisplayToastAsync(LN.AutoupdateFailed);
```

And here's exception stack:
```cs
Xamarin.CommunityToolkit.UI.Views SnackBar.Show (Xamarin.Forms.Page sender, Xamarin.CommunityToolkit.UI.Views.Options.SnackBarOptions arguments)
Xamarin.CommunityToolkit.Extensions PageExtension.DisplayToastAsync (Xamarin.Forms.Page page, System.String message, System.Int32 durationMilliseconds)
```

`Shell.Current.CurrentPage` is not null before (since method gets called) and after (checked in `catch` block) `DisplayToastAsync` execution.

**Update**: It crashes on this line:
![image](https://user-images.githubusercontent.com/6609929/108738699-926c7100-753c-11eb-9e2b-75f9cfbb3397.png)
![image](https://user-images.githubusercontent.com/6609929/108744074-2db41500-7542-11eb-83ab-0f05ea12218c.png)

### Steps to Reproduce

1. Create Shell app with TabbBar and two tabs
2. Create button on one of the tabs that executes this code:
```cs
await Shell.Current.GoToAsync("RouteToOtherTab");
try
{
    await Shell.Current.CurrentPage.DisplayToastAsync("");
}
catch (Exception ex)
{
    await Shell.Current.CurrentPage.DisplayAlert("Error", ex.ToString(), "Ok");
}
```
3. Press the button

### Expected Behavior
Displaying toast or snackbar doesn't throw exception

### Actual Behavior
Displaying toast or snackbar throws exception

### Basic Information

- Version with issue: 1.0.3
- Last known good version: -
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android: 11
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround
Wrap every `DisplayToastAsync` and `DisplaySnackBarAsync` in try-catch

### Reproduction imagery

![xct3](https://user-images.githubusercontent.com/6609929/108751683-30673800-754b-11eb-8bb2-551de991ebf2.gif)

### Reproduction Link

[App7.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/6037737/App7.zip)

**Comment by maxkoshevoi** [comment] 2021-02-24 17:25
@pictos 
- Created app that reproduces the error (zip is in the issue description)
- This appears to be shell only and when switching between tabs. Tested it with `Navigation.Pop`, issue didn't happen.

**Comment by pictos** [comment] 2021-02-25 01:41
Looks like that's a Shell issue because the GoToAsync returns but the Page Renderer isn't created yet. So the issue isn't with our code and with Shell navigation, I suppose. 
When I add that `Task.Delay` everything works as expected. I saw that before in some Shell Navigation areas. I'm very tempted to close this issue, but first I would like to have a @PureWeen input here.
```csharp
 private async Task Button_Clicked()
        {
            await Shell.Current.GoToAsync("//tabbar/About");
			try
			{
				await Task.Delay(10);
				await Shell.Current.CurrentPage.DisplayToastAsync(string.Empty);
			}
			catch (Exception ex)
			{
				await Shell.Current.CurrentPage.DisplayAlert("Error", ex.ToString(), "Ok");
			}
		}
```

**Closed** 2021-04-19 17:57 UTC
Labels: bug, needs-more-discussion, not-up-for-grabs
