### ISSUE TITLE
[Bug] SnackBar actions only display one action

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/XamarinCommunityToolkit#475] opened 2020-10-21 08:05 UTC
No matter how actions you add to a SnackBar, only one action is displayed.

Considering it wants an enumeration of actions I am assuming it should display all of them?

**Comment by VladislavAntonyuk** [comment] 2020-10-22 04:29
Please add the platform. On Android we use native Snackbar, which have only 1 button. To be consistent with Android, the same for iOS. Other platforms have multiple buttons

**Comment by roubachof** [comment] 2020-10-22 06:47
@Tommigun1980 please don't open several issues on the same subject. Duplicate of #476

**Comment by Tommigun1980** [comment] 2020-10-22 12:32
> @Tommigun1980 please don't open several issues on the same subject. Duplicate of #476

It's not a duplicate. The other one has three feature suggestions not related to this. In that report I touched upon this and wrote 'not sure if it's a bug as it accepts an enumeration of actions', and filed a bug report about it.

I thought feature requests and bug reports should not be combined.

**Comment by jfversluis** [comment] 2020-10-22 12:36
If we can only have one, we should at least also make this reflect in code and not let developers add any more actions which they will then expect to show up

**Comment by Tommigun1980** [comment] 2020-10-22 12:36
> Please add the platform. On Android we use native Snackbar, which have only 1 button. To be consistent with Android, the same for iOS. Other platforms have multiple buttons

Thank you. I wonder if Actions should be platform dependent then? I mean you can't share the code calling it anyway in a meaningful way, or at the very least it is imho unexpected behaviour that it's semi random what gets shown on what platform.

**Comment by AndreiMisiukevich** [comment] 2020-12-10 23:41
@VladislavAntonyuk @jfversluis any ideas about this issue?)

**Comment by VladislavAntonyuk** [comment] 2020-12-11 05:22
@AndreiMisiukevich It is the only Android issue, because it only supports 1 action button.

**Comment by pictos** [comment] 2021-01-10 23:12
@VladislavAntonyuk so this is a limitation on the platform that we can't handle?

**Comment by VladislavAntonyuk** [comment] 2021-01-10 23:37
If we are talking about native Android Snackbar then yes.
But we can implement it with custom layout like other platforms.

**Comment by pictos** [comment] 2021-01-11 00:42
@VladislavAntonyuk thanks for the answer, so I'll let this open and this should be an enhancement and not a bug. So if you or any one that wants to work this should target the `develop` branch.

**Comment by brminnick** [comment] 2021-11-11 02:17
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin

**Closed by brminnick** 2021-11-11 02:17 UTC
Labels: ready-to-implement, enhancement, up-for-grabs, a/Snackbar
